### ISSUE TITLE
show connection status

### ISSUE THREAD

**Issue by gitkent** [jonmosco/kube-ps1#100]
It would be good to show my current connection status whether I am logged-in or logged-out from the kubernetes cluster. For instance:

(my-cluster:my-namespace LOGGED-IN)

(my-cluster:my-namespace LOGGED-OUT)

perhaps, LOGGED-in in green colour and LOGGED-OUT in yellow colour. Ideally, there should be an option to switch this feature on/off.

Thanks

**Comment by jonmosco** [comment]
This is out of scope for the project, but i'm sure it would be simple to add a hook in your prompt to be able to display that value.
