### ISSUE TITLE
KUBE_PS1_CONTEXT not changing when using kubectx quickly

### ISSUE THREAD

**Issue by Aracki** [jonmosco/kube-ps1#105]
If you quickly changing contexts (with `kubectx -`) you will realize that: <br> `$KUBE_PS1_CONTEXT` and `kubectl config current-context` can give you different values.

AFAIK, this is happening when the rate of switching is less than 1 second.

**Comment by bassco** [comment]
@Aracki  The precision of `$(date +%s)` is 1 second, which will explain the issue you are experiencing.

You can try and work around this by adding a `return 0` at the start of the `_kube_ps1_file_newer_than` function.

**Comment by zhorvath-branch** [comment]
@bassco Wow, this really helped, thanks! Was running into a similar issue with the zsh plugin.

**Comment by Huang-Wei** [comment]
Any particular reason to use `zstat` instead of `stat` for zsh?

https://github.com/jonmosco/kube-ps1/blob/54271c7e0c890779eab058c8a9661d88e410de72/kube-ps1.sh#L193-L197

BTW: why not use EPOCH time in **nanoseconds**: `stat --format='%.Y' <kube_config>`:

```
$ stat --format='%.Y' ~/.kube/config
1641623641.282559266
$ date +%s.%N
1642555362.984111000
```
