### ISSUE TITLE
Loading is slow when using zsh module

### ISSUE THREAD

**Issue by TheMikeyR** [jonmosco/kube-ps1#107]
Using zsh 5.1.1 and the kube-ps1 module included from git. When starting a new terminal, the terminal takes ~1 sec before I can use the prompt, after loading everything is snappy and fast. It's only on a new terminal window. If i uncomment kube-ps1 from my plugins list, it loads in ~0.2 sec. 

Using zprof doesn't detect what stalls it, and if I'm using ``time zsh -i -c exit`` it also shows a fast time. So I have a hard time debugging the issue.  

I'm using pure, but removing load of pure doesn't increase loading speed.

**Comment by florianrusch** [comment]
Do I understand this correct, you have kube-ps1 in the plugins list of zsh?
I'm using oh-my-zsh and installed kube-ps1 via homebrew and just added `$(kube_ps1)` into my theme.

Example (robbyrussel.zsh-theme):
```
local ret_status="%(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ )"
PROMPT='${ret_status} $(kube_ps1) %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)'

ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg_bold[blue]%}git:(%{$fg[red]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%} "
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[blue]%}) %{$fg[yellow]%}✗"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[blue]%})"
```

**Comment by TheMikeyR** [comment]
@florianrusch correct, I'm using Ubuntu 16.04 and using it as a plugin for oh-my-zsh.

**Comment by TheMikeyR** [comment]
I've fixed it by removing it from my plugins list and added `source /home/mikeyr/dev/github/others/kube-ps1/kube-ps1.sh` instead in my `.zshrc`
