### ISSUE TITLE
Check to see if LANG is set before continuing?

### ISSUE THREAD

**Issue by TJM** [jonmosco/kube-ps1#108]
I have just fought my way through #95 and think that maybe some code could be added to bail out if the locale is not set (`LANG`).  I am not sure if it would work or not, but it would be a lot less surprising to see an ERROR while parsing the profile than to have bash crash. I am not sure, however, whether something like an `exit 1` is going to make someone any happier that they cannot login to their system after adding this. However, at least the cause would be easier to detect and solve.

At a minimum, there should probably be some documentation around not adding kube-ps1.sh directly to `/etc/profile.d` on Red Hat style OS's. It needs to be named such that it will be parsed *after* `/etc/profile.d/lang.sh`, which set the `LANG` environment variable. I added a "z" to the front of mine (`zkube-ps1.sh`).

**Comment by jonmosco** [comment]
This is more of an environment configuration issue than one directly related to kube-ps1.  Exit status for the script itself.  Global profiles on the system would be a decision for the admin/user if they would want to add any 3rd party code to it, hence the usage of a `.bash{rc,_profile}`.
Nevertheless, thank you for using the project.

**Comment by TJM** [comment]
Hi @jonmosco ,

Thanks for looking into this.

Hopefully my comment at the end of the other issue (95) will help someone else running into this issue, which is that the locale (LANG) must be set before you can source this code, else bash will crash. It probably only affects people trying to setup a bastion host or something similar where, instead of setting every tool up on a per-user basis, they may want to set things up globally (/etc/profile.d). 

~tommy

**Comment by VarunTyagi86** [comment]
@TJM : I am facing the similar issue, could you please let me know the workaround. I am using centos7.3 and bash crashes as soon as i run command source /opt/file/zkube-ps1.sh . Please suggest what i am doing wrong ?

**Comment by TJM** [comment]
@VarunTyagi86 You need to make sure that wherever you source the kube-ps1 (/etc/profile.d?) that it is *after* LANG is set. I see you renamed /opt/file/zkube-ps1.sh, but its the symlink in /etc/profile.d that needs the "z" in the name. It may also be the case that centos 7.3 is  too old to handle the International character? I do not have 7.3 to be able to test. Basic workaround would be to edit the file on a newer system to remove the emoji.
