### ISSUE TITLE
error on ubuntu

### ISSUE THREAD

**Issue by crixo** [jonmosco/kube-ps1#111]
I'm loading the kube-ps1.sh in the .bashrc as described but I'm getting the following error
```
modglue::ext_process::determine_path_: executable helper not found
```

Regardless the error, the tools works but it does not update the context/ns if i change it with the CLI (kubectx for ex.) unless I reload the shell (source ~/.bashrc) 

I'm using windows 10 linux subsystem
uname -a
Linux LI-029 4.4.0-17763-Microsoft #864-Microsoft Thu Nov 07 15:22:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

**Comment by jonmosco** [comment]
I don't have a windows system around to test this out.   Did you try to load bash without any default settings and run the script that way as per the docs?

**Comment by crixo** [comment]
> I don't have a windows system around to test this out. Did you try to load bash without any default settings and run the script that way as per the docs?

Yes same issue.
```
crixo@XX-XXX:~
source ~/.bashrc
modglue::ext_process::determine_path_: executable helper not found
[crixo@XX-XXX ~ (⎈ |kind-plain:default)]$
````
now the .bashrc is simply the following as per documentation
```
source ~/kube-ps1.sh
PS1='[\u@\h \W $(kube_ps1)]\$ '
```

**Comment by Salec** [comment]
Same issue here


![image](https://user-images.githubusercontent.com/4624133/73406682-e0686400-42ab-11ea-8d9d-e95670e8980e.png)

**Comment by feksai** [comment]
@Salec , check that line ending of kube-ps1.sh is LF (not CRLF). For me that fixed the issue
![image](https://user-images.githubusercontent.com/8003006/75040774-54bdae00-54cc-11ea-8993-78010eeecceb.png)

**Comment by jonmosco** [comment]
@Salec Going to close this for the fix mentioned above.
