### ISSUE TITLE
Unable to Install kube-ps1

### ISSUE THREAD

**Issue by VarunTyagi86** [jonmosco/kube-ps1#113]
I am unable to install the kube-ps1.sh on CentOS Linux release 7.3.1611 (Core). Getting Below error while sourcing source /opt/files/kube-ps1.sh

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:51:13Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**ERROR**

+ [[ -n '' ]]
+ KUBE_PS1_BINARY=kubectl
+ KUBE_PS1_SYMBOL_ENABLE=true
*** Error in `sh': double free or corruption (out): 0x00000000023feed0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81679)[0x7fc7360f4679]
sh[0x422d6a]
sh[0x424671]
sh(yyparse+0x3c9)[0x426369]
sh(parse_command+0x5a)[0x41df4a]
sh(read_command+0x5c)[0x41e00c]
sh(reader_loop+0x11c)[0x41e20c]
sh(main+0xc4e)[0x41c8ee]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7fc736095505]
sh[0x41d38a]
======= Memory map: ========
00400000-004dd000 r-xp 00000000 08:01 393483                             /usr/bin/bash
006dc000-006dd000 r--p 000dc000 08:01 393483                             /usr/bin/bash
006dd000-006e6000 rw-p 000dd000 08:01 393483                             /usr/bin/bash
006e6000-006ec000 rw-p 00000000 00:00 0
023f9000-0241a000 rw-p 00000000 00:00 0                                  [heap]
7fc730000000-7fc730021000 rw-p 00000000 00:00 0
7fc730021000-7fc734000000 ---p 00000000 00:00 0
7fc735c4a000-7fc735c5f000 r-xp 00000000 08:01 656244                     /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7fc735c5f000-7fc735e5e000 ---p 00015000 08:01 656244                     /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7fc735e5e000-7fc735e5f000 r--p 00014000 08:01 656244                     /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7fc735e5f000-7fc735e60000 rw-p 00015000 08:01 656244                     /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7fc735e60000-7fc735e6c000 r-xp 00000000 08:01 656300                     /usr/lib64/libnss_files-2.17.so
7fc735e6c000-7fc73606b000 ---p 0000c000 08:01 656300                     /usr/lib64/libnss_files-2.17.so
7fc73606b000-7fc73606c000 r--p 0000b000 08:01 656300                     /usr/lib64/libnss_files-2.17.so
7fc73606c000-7fc73606d000 rw-p 0000c000 08:01 656300                     /usr/lib64/libnss_files-2.17.so
7fc73606d000-7fc736073000 rw-p 00000000 00:00 0
7fc736073000-7fc736236000 r-xp 00000000 08:01 656222                     /usr/lib64/libc-2.17.so
7fc736236000-7fc736436000 ---p 001c3000 08:01 656222                     /usr/lib64/libc-2.17.so
7fc736436000-7fc73643a000 r--p 001c3000 08:01 656222                     /usr/lib64/libc-2.17.so
7fc73643a000-7fc73643c000 rw-p 001c7000 08:01 656222                     /usr/lib64/libc-2.17.so
7fc73643c000-7fc736441000 rw-p 00000000 00:00 0
7fc736441000-7fc736443000 r-xp 00000000 08:01 656239                     /usr/lib64/libdl-2.17.so
7fc736443000-7fc736643000 ---p 00002000 08:01 656239                     /usr/lib64/libdl-2.17.so
7fc736643000-7fc736644000 r--p 00002000 08:01 656239                     /usr/lib64/libdl-2.17.so
7fc736644000-7fc736645000 rw-p 00003000 08:01 656239                     /usr/lib64/libdl-2.17.so
7fc736645000-7fc73666a000 r-xp 00000000 08:01 395579                     /usr/lib64/libtinfo.so.5.9
7fc73666a000-7fc73686a000 ---p 00025000 08:01 395579                     /usr/lib64/libtinfo.so.5.9
7fc73686a000-7fc73686e000 r--p 00025000 08:01 395579                     /usr/lib64/libtinfo.so.5.9
7fc73686e000-7fc73686f000 rw-p 00029000 08:01 395579                     /usr/lib64/libtinfo.so.5.9
7fc73686f000-7fc736891000 r-xp 00000000 08:01 656210                     /usr/lib64/ld-2.17.so
7fc736a88000-7fc736a8b000 rw-p 00000000 00:00 0
7fc736a8d000-7fc736a90000 rw-p 00000000 00:00 0
7fc736a90000-7fc736a91000 r--p 00021000 08:01 656210                     /usr/lib64/ld-2.17.so
7fc736a91000-7fc736a92000 rw-p 00022000 08:01 656210                     /usr/lib64/ld-2.17.so
7fc736a92000-7fc736a93000 rw-p 00000000 00:00 0
7ffc1c2fb000-7ffc1c31c000 rw-p 00000000 00:00 0                          [stack]
7ffc1c3bb000-7ffc1c3bd000 r--p 00000000 00:00 0                          [vvar]
7ffc1c3bd000-7ffc1c3bf000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted
bash: kube_ps1: command not found

**Comment by smlx** [comment]
This is https://github.com/jonmosco/kube-ps1/issues/95. TL;DR it's a bug in your shell.

**Comment by jonmosco** [comment]
Yes, please check your shell configuration and take a look at issue #95
