### ISSUE TITLE
-kube-ps1/kube-ps1.sh:27: character not in range when installing with zinit plugin manager

### ISSUE THREAD

**Issue by jdambly-ns** [jonmosco/kube-ps1#114]
when trying to install kubeps1 with zinit I am getting the following error

➜  ~ zplugin light jonmosco/kube-ps1

Downloading jonmosco/kube-ps1... (as jonmosco/kube-ps1...)

Cloning into '/home/jdambly/.zinit/plugins/jonmosco---kube-ps1'...
◥ ████ OBJ: 100, PACK: 551/551, COMPR: 100%, REC: 100%, RES: 100%
Compiling kube-ps1.sh.
/home/jdambly/.zinit/plugins/jonmosco---kube-ps1/kube-ps1.sh:27: character not in range

**Comment by smlx** [comment]
probably your locale / lang settings aren't utf8: https://github.com/jonmosco/kube-ps1/issues/80

**Comment by ChTBoner** [comment]
I confirm that should fix it. Add the same issue.
Editing my zshrc file with 
```bash
export LC_ALL=fr_FR.UTF-8
export LANG=fr_FR.UTF-8 
```
fixed it

**Comment by jonmosco** [comment]
Thank you for the suggested fixes.

**Comment by xiaohui-zhangxh** [comment]
> 

I don't why this does't work when I ssh to remote wsl from Mac iTerm. Finally I stopped error message with:

```shell
# ~/.zshrc

UNICODE_TEST=$(echo '\u2190' 2>/dev/null);
if [ -z $UNICODE_TEST ]; then
    KUBE_PS1_SYMBOL_DEFAULT='x'
fi

source $ZSH/oh-my-zsh.sh
```

**Comment by lsgrep** [comment]
You have to put the `LC_ALL` and `LANG` at the top.
