### ISSUE TITLE
oh-my-zsh integration

### ISSUE THREAD

**Issue by airmonitor** [jonmosco/kube-ps1#116]
Hey Jon,

I'm wondering if you can advice how I can use both zsh integration at the same time.
I have a simple .zshrc file:
export ZSH="/home/tom/.oh-my-zsh"
ZSH_THEME="powerlevel9k/powerlevel9k"
plugins=(git)
source $ZSH/oh-my-zsh.sh
source ~/.local/share/kube-ps1/kube-ps1.sh
autoload -U compinit && compinit
PROMPT='$(kube_ps1)'$PROMPT

and sadly I can't see kube-ps1 prompt when powerlevek9k theme is loaded.

when I ran:
zsh --no-rcs
source /home/tom/.local/share/kube-ps1/kube-ps1.sh
PROMPT='$(kube_ps1)'$PROMPT

kube prompt is started but... I'm wondering if it will be possible to have them both running, like overwrite powerlevel9k theme when kubens/kubectx/kubectl were invoked in any way?

**Comment by Gounlaf** [comment]
try with oh-my-zsh plugin instead of installing it yourself

```
plugins=(
  git
  kube-ps1
) 
```

PROMPT redefinition (`PROMPT='$(kube_ps1)'$PROMPT`) is still needed for me

**Comment by NicolasRouquette** [comment]
Thanks @Gounlaf ; with antigen, I used your advice like this in my `~/.zshrc`:

```
source ...

antigen use oh-my-zsh
...
antigen bundle kube-ps1
...
antigen apply

PROMPT='$(kube_ps1)'$PROMPT
```

**Comment by jonmosco** [comment]
Looks good, that advice should get your prompt configured properly.  Thank you for the suggestions @Gounlaf !!
