### ISSUE TITLE
Allow customization of the symbol

### ISSUE THREAD

**Issue by Nuru** [jonmosco/kube-ps1#117]
At the moment (version v0.7.0), `kube-ps1` allows for a choice of 2 symbols (or no symbol) in the prompt:

- The default, [HELM SYMBOL](https://www.fileformat.info/info/unicode/char/2388/index.htm), Unicode \u2388
- The alternate ("IMG"), [WHEEL OF DHARMA](https://www.fileformat.info/info/unicode/char/2638/browsertest.htm),  Unicode \u2638

I would prefer to directly specify the symbol to use, for a few reasons:
1. At the moment, with `KUBE_PS1_SYMBOL_ENABLE=false`, my prompt is showing `root2388` rather than a default symbol. 
2. Setting `KUBE_PS1_SYMBOL_ENABLE=true` and `KUBE_PS1_SYMBOL_USE_IMG=true` yields the non-emoji version of the character in MacOS Terminal:
![image](https://user-images.githubusercontent.com/2793313/77257512-27cafb00-6c32-11ea-9a4f-051586674b50.png)
instead of 
![image](https://user-images.githubusercontent.com/2793313/77257523-374a4400-6c32-11ea-9803-4fe2af996d51.png)

I don't know about the first problem and don't want to spend the time looking into it, but the second problem is resolved by setting the character to display the emoji variant via the variant code, in other words, by setting the image character to be `\u2638\ufe0f`.  So it would be sufficient for me to just be able to set `KUBE_PS1_SYMBOL=$'\u2638\ufe0f'`. This would also allow other people to use whatever other symbol they want.

**Comment by Sher-Chowdhury** [comment]
@Nuru Thanks for your suggestion. This got the image working for me on my macOS. 

```
KUBE_PS1_SYMBOL_ENABLE=true
KUBE_PS1_SYMBOL_DEFAULT=$'\u2638\ufe0f '
KUBE_PS1_SYMBOL_USE_IMG=false
```

**Comment by Nuru** [comment]
Thanks, @Sher-Chowdhury that works for me. I misunderstood the nature of `KUBE_PS1_SYMBOL_DEFAULT`
