### ISSUE TITLE
Update prompt when kubecfg file is deleted

### ISSUE THREAD

**Issue by Nuru** [jonmosco/kube-ps1#118]
If the prompt shows a configuration for a valid `kubecfg` file and that file is deleted, the prompt does not update. It should update and show whatever it would show if that file did not exist at startup. 

I think the issue is https://github.com/jonmosco/kube-ps1/blob/c685ac80c14605f47a440018e2d03aff58683c81/kube-ps1.sh#L221-L227
does not ever do anything if it cannot find a `kubecfg` file. It needs some way to detect (and probably cache) that there is no valid configuration available and update the prompt accordingly.

**Comment by jonmosco** [comment]
In the `_kube_ps1_update_cache()` function, there is checking for the KUBECONFIG env variable.  If that is not found, it will move on to the .kube/config file:

```
  if [[ "${KUBECONFIG}" != "${KUBE_PS1_KUBECONFIG_CACHE}" ]]; then
    # User changed KUBECONFIG; unconditionally refetch.
    KUBE_PS1_KUBECONFIG_CACHE=${KUBECONFIG}
    _kube_ps1_get_context_ns
    return
  fi

  # kubectl will read the environment variable $KUBECONFIG
  # otherwise set it to ~/.kube/config
```

**Comment by Nuru** [comment]
@jonmosco This issue is about when  `"${KUBECONFIG}" == "${KUBE_PS1_KUBECONFIG_CACHE}"` but the kubeconfig file is deleted.

**Comment by jonmosco** [comment]
Fix in place with latest commit.  Big improvement for caching that updates the prompt accordingly.  Sorry for how long this took, and thank you for the issue.
