### ISSUE TITLE
Kube-PS1 Wont work with ZSH.

### ISSUE THREAD

**Issue by akhr** [jonmosco/kube-ps1#121]
The installation instructions are confusing for ZSH. Do you want us to use Zplugin to install your tools or do brew install kube-ps1 and then add the following to .zshrc?
```
source "path/kube-ps1/kube-ps1.sh"
PS1='$(kube_ps1)'$PS1
```
Either ways I don't see the kube-ps1 prompt in my iterm2 terminal. 
Note:Bash shell works fine

**Comment by RobCodemonkey** [comment]
Can confirm that this does not work for zsh on catalina at least. Independent of the method used to install kube-ps1, I still get no prompt change.

**Comment by jonmosco** [comment]
Zplugins are used to extend the functionality of the shell, such as the zstat plugin that is not loaded by default. 

Installing the prompt helper should be done with the source command after either cloning this repository, or using Brew. 

What problems are you experiencing?  Did you download and source the plugin in your prompt?  Can you paste the section of your configuration file that contains the prompt ?

**Comment by superbeer** [comment]
i'm  use zsh but don't work.  i installing by 

```
$ brew update
$ brew install kube-ps1
```
and add ~/.zshrc
source /usr/local/opt/kube-ps1/share/kube-ps1.sh
PS1='$(kube_ps1)'$PS1

**Comment by jonmosco** [comment]
I tried this on my install as well in some zsh containers as well.  Did you try running `kubeon` just to make sure that isn't the issue?

**Comment by superbeer** [comment]
i'm run` kubeon`

ps i'm install on mac os

**Comment by superbeer** [comment]
It is  work 
It is error from some theme   (ZSH_THEME)
sorry from my mistake.

**Comment by jonmosco** [comment]
Glad to hear!

**Comment by pierregambaud** [comment]
On my **M1**, editing `.zshrc` by adding the following two lines solved my issue:

```
source "/opt/homebrew/opt/kube-ps1/share/kube-ps1.sh"
PS1='$(kube_ps1)'$PS1
```

**Comment by bulmust** [comment]
If you are using oh-my-zsh, `PROMPT='$(kube_ps1)'$PROMPT;kubeoff` should be after `source $ZSH/oh-my-zsh.sh` line.
