### ISSUE TITLE
Context does not refresh..

### ISSUE THREAD

**Issue by nijel91** [jonmosco/kube-ps1#124]
Hello.

When I switch context, it does not seem to refresh until I open a new terminal. 
I can run kubectl set use-context abcd to change it from xyz. I will get a message that it was changed to abcd, but context will still show xyz.

It is possible that I am doing something wrong, but it does show correctly if I open new terminal window. 
I am doing this thru VS Code with default terminal being Git Bash. 

Any ideas or suggestions would be greatly appreciated!
Thank you.

Vitaly

**Comment by meganzhao10** [comment]
I am facing the same issue - both the context and namespace don't refresh until I open a new shell session. I have tried disabling and reenabling the prompt with `kubeon` and `kubeoff` and the prompt still didn't refresh.

**Comment by jonmosco** [comment]
Are you running this on a windows system in the bash shell for VS code or on a Linux system?

**Comment by georgettica** [comment]
hello! I have a similar issue and may have more context..
running inside a `fedora` container and when I remove the kubeconfig (from ~/.kube/config) I still see the previous cluster name

**Comment by georgettica** [comment]
Disregard me. The issue is not reproducing, thanks to @staswiner

**Comment by jonmosco** [comment]
No worries.  I will close this issue.
