### ISSUE TITLE
Allow omitting space after the k8s icon

### ISSUE THREAD

**Issue by laur89** [jonmosco/kube-ps1#126]
When defining the `KUBE_PS1_SYMBOL_DEFAULT`, we can omit the space after the icon ourselves;
however, if `KUBE_PS1_SYMBOL_USE_IMG=true` is set, then [following](https://github.com/jonmosco/kube-ps1/blob/master/kube-ps1.sh#L155) block is executed, and we're forced to have a space after the icon.

Perhaps the icon padding should be made globally optional & maybe configurable?

**Comment by jonmosco** [comment]
Yes, this is possible.  The space (padding) was a fix for the character not having proper spacing.
