### ISSUE TITLE
Error "bash: kube_ps1: command not found" in root in mac

### ISSUE THREAD

**Issue by Don1008** [jonmosco/kube-ps1#127]
When i switch to root user in mac it shows "bash: kube_ps1: command not found" error. Also it does not recognizes any kube_ps1 command, such as kubeon or kubeoff. This is happening on mac where I have installed bash through brew.

**Comment by jonmosco** [comment]
The root users shell configuration will not be the same as your users shell configuration.  If you want to use this as root, you have to configure your shell appropriately.
