### ISSUE TITLE
Custom cluster & namespace functions not working

### ISSUE THREAD

**Issue by mecampbellsoup** [jonmosco/kube-ps1#129]
In my `.zshrc` file I have the following config related to `kube-ps1` (installed via `brew install kube-ps1`):

```
plugins=(kube-ps1 zsh-syntax-highlighting history git rake rails zsh-completions tmux tmuxinator yarn kubectl)

# kube-ps1
function get_cluster_short() {
  #echo $1
  #short=$(echo "$1" | cut -d . -f1)
  #return short
  echo "$1" | cut -d . -f1
}
export KUBE_PS1_CLUSTER_FUNCTION=get_cluster_short

function get_namespace_upper() {
  echo "$1" | tr '[:lower:]' '[:upper:]'
}

export KUBE_PS1_NAMESPACE_FUNCTION=get_namespace_upper

PROMPT='$(kube_ps1)'$PROMPT
```

However, it doesn't seem like my custom cluster/namespace functions are being applied to my prompt. Before & after sourcing this file with those functions added, my prompt looks like:

```bash
(⎈ tenant-matt-user-tenant-matt-tenant-cluster.chi.atlanticcrypto.com:tenant-matt)➜  ~ zshconfig
(⎈ tenant-matt-user-tenant-matt-tenant-cluster.chi.atlanticcrypto.com:tenant-matt)➜  ~ source ~/.zshrc
(⎈ tenant-matt-user-tenant-matt-tenant-cluster.chi.atlanticcrypto.com:tenant-matt)➜  ~ kubens -c
tenant-matt
(⎈ tenant-matt-user-tenant-matt-tenant-cluster.chi.atlanticcrypto.com:tenant-matt)➜  ~ kubectx -c
tenant-matt-user-tenant-matt-tenant-cluster.chi.atlanticcrypto.com
(⎈ tenant-matt-user-tenant-matt-tenant-cluster.chi.atlanticcrypto.com:tenant-matt)➜  ~ declare -f get_cluster_short
get_cluster_short () {
        echo "$1" | cut -d . -f1
}
```

**Comment by AlyRagab** [comment]
I have the same issue

**Comment by dmitry-mightydevops** [comment]
Same thing on my side. 

```bash
function get_cluster_name() {
  name1=`echo $1 | awk -F "/" '{print $2}'` | tr '[:lower:]' '[:upper:]'
  name2=`echo $1 | awk -F "/" '{print $1}'` | tr '[:lower:]' '[:upper:]'

  [ -v "$name1" ] && echo $name2 || echo $name1
}

export KUBE_PS1_NAMESPACE_FUNCTION=get_cluster_name
PROMPT='$(kube_ps1)'$PROMPT

```

**No effect**

**Comment by georgettica** [comment]
odd, my cluster function does work.. I am running it in a fedora container 🥵 
https://github.com/openshift/ocm-container/blob/b9654cb5e1dd83c3e154f609c9918b82a8cff66f/container-setup/utils/bashrc_supplement.sh#L10

**Comment by jonmosco** [comment]
Works good for me as well.  Did you try to default your environment and just use the plugin standalone to test?

**Comment by georgettica** [comment]
I am using bash, not zsh 😨 
If this helps point the issue

**Comment by jonmosco** [comment]
Ok, you can still try it with `bash --norc` , load the plugin, and see if  your custom functions work.

**Comment by georgettica** [comment]
When you say "load the plugin"
What do you mean?
I have always sourced the script, is that what you mean?

**Comment by jonmosco** [comment]
Yes, sorry.  I default to calling it a plugin.

**Comment by georgettica** [comment]
I might have confused the two.
Will test this better tomorrow

**Comment by jonmosco** [comment]
Just tested and this appears to be working for me.  Going to close this issue unless I hear otherwise.
