### ISSUE TITLE
retake demo.gif

### ISSUE THREAD

**Issue by ahmetb** [jonmosco/kube-ps1#13]
It looks like it's outdated.

It can now use `kubeon`/`kubeoff`, along with the usual kubectx/kubens jazz!

**Comment by jonmosco** [comment]
Yes, will do.  What utility did you use for creating the gifs for kubectx/kubens?  They look smooth.

**Comment by ahmetb** [comment]
asciinema + asciicast2gif. I can't say they're very efficient in size unfortunately as asciicast2gif actually renders the asciicast and records screencast = bad idea.

**Comment by ahmetb** [comment]
I tried to take it but the GIF turned out crappy because asciinema's gif creator doesn't support fancy characters. I reported this issue to their repo before.

if you wanna use my embed: https://asciinema.org/a/4tG2AfPWVjn8DErDTMGQGD8F8

![ps1](https://user-images.githubusercontent.com/159209/34586746-2d2df1c4-f15a-11e7-9701-148be2484e73.gif)

**Comment by jonmosco** [comment]
I ran into the problem before so I ended up using gifox.  I uploaded a new gif that shows most of the features, just doesnt display the color of the fancy prompt.

**Comment by ahmetb** [comment]
hmm I thought those `prompt_*` stuff is real. I don't recommend making demos like that. I still like mine because it runs faster and small in terms of both pixels and file size. but feel free to definitely close this.

**Comment by jonmosco** [comment]
Agreed.  Took your lead and made a new demo.  Looks pretty good this time.  Thanks again.  Saw the tweet with the img you created as well, very cool.  Fun project!
