### ISSUE TITLE
set different color per cluster

### ISSUE THREAD

**Issue by omriarieli** [jonmosco/kube-ps1#131]
Hi, apologies  if this has been asked i have looked at issues and could not find my answer.
am i to assume KUBE_PS1_CTX_COLOR= doesnt support function calling like KUBE_PS1_CLUSTER_FUNCTION does?
I am trying to set the cluster name color to be different according to the name. for like if the name contains prod cluster color will be red else cluster color will be blue. so i have a visual que which cluster im in to avoid mistakes :)

i tried adding to .zshrc a function but it justs disables the color in cluster part of prompt
what am i doing wrong?
love the project!!!

```function get_cluster_name() {

case $1 in

  *'prod'*)
    echo 'red'
    ;;
esac
}

KUBE_PS1_CTX_COLOR=get_cluster_name

**Comment by tux-00** [comment]
@omriarieli 
As a temporary "fix" I added these lines at the top of the kube_ps1 function into .kube-ps1.sh :
```
if [[ $KUBE_PS1_CONTEXT == prod-* ]]; then
  KUBE_PS1_CTX_COLOR=15
  KUBE_PS1_BG_COLOR=red
else
  KUBE_PS1_CTX_COLOR=blue
fi
```

**Comment by omriarieli** [comment]
@tux-00  great, works like a charm
thank you very much for the tip!!
ill close this now
