### ISSUE TITLE
Bash installation ERROR

### ISSUE THREAD

**Issue by hamidgholami** [jonmosco/kube-ps1#139]
Hello dear,

After clone the project and change `~/.bashrc` based on documentation, This error is shown:
```bash
: command not found
: command not found
: command not found
: command not found
: command not found
-bash: /home/hamidgholami/kube-ps1/kube-ps1.sh: line 47: syntax error near unexpected token `elif'
'bash: /home/hamidgholami/kube-ps1/kube-ps1.sh: line 47: `elif [ "${BASH_VERSION-}" ]; then
kube_ps1: command not found
```
I checked master branch and `v0.7.0` tag.
Could you please help me for install `kube-ps1` on bash?
Thank you,
Hamid

**Comment by jonmosco** [comment]
This looks like it is a bash configuration issue.
