### ISSUE TITLE
Differentiate terminal colors based on context

### ISSUE THREAD

**Issue by briantopping** [jonmosco/kube-ps1#144]
Hi, thanks for this robust effort! kube-ps1 is one of the first things I set up on a new machine. 

I think it could be great if the tool could somehow differentiate between contexts somehow, for instance with a color. In order to make this automatic, it might be great if the color was generated by a hash of the context name modulo the number of colors that are available for display. This might get tricky due to the background color of a terminal though. 

That leads me to wonder if the entire terminal might be colorized based on the context. For instance, context names could match a regex to decide whether to the background red for production clusters, blue for development, etc.

Just looking for ways to reduce errors. It's always 4am somewhere in the world!!

**Comment by jonmosco** [comment]
The prompt can have color options as listed in the README, but having dynamic colors is beyond the scope of this project. If you check out the custom function option, that might be a solution for you as well.
Thanks for using the project!
