### ISSUE TITLE
feat: it'd be cool if kube-ps1 could turn on/off if the pwd has .yaml or other k8s associated files in it

### ISSUE THREAD

**Issue by snickell** [jonmosco/kube-ps1#147]
This would automatically hide the prompt in most folders on a system, and show it when in a "kubernetes related directory"

**Comment by jonmosco** [comment]
This can prob be done with a shell function.  The prompt can be turned on and off with the kube-off and kube-on functions, but keeping it available no matter the directory is essential to some workflows (and the way I use it).  Thank you for using the project!
