### ISSUE TITLE
Turn off by default when launching zsh

### ISSUE THREAD

**Issue by stefanzilske** [jonmosco/kube-ps1#149]
Hey folks,

I just installed kube-ps1 using Homebrew and it works fine in iTerm2 with oh-my-zsh. But I would like to switch if off by default and only activate it with `kubeon` when I need it. `kubeoff -g` doesn't work, when I close and launch iTerm2 again, it's activated.

Setting `KUBE_PS1_ENABLED = false` in `.zshrc` does have no effect either. How can I achieve that?

Cheers,
Stefan

**Comment by jonmosco** [comment]
The oh-my-zsh port has been updated with the latest code. Can you update and check if this corrects the issue?  (assuming you are using oh-my-zsh).

**Comment by jonmosco** [comment]
Did you try the latest update of the oh-my-zsh port?

**Comment by jonmosco** [comment]
if you want to have it disabled upon startup, you could create an empty file named `disabled` in ~/.kube/kube-ps1
