### ISSUE TITLE
Support for cloud providers

### ISSUE THREAD

**Issue by obvionaoe** [jonmosco/kube-ps1#151]
Hi, would it be possible to add support for clusters from cloud providers, such as: GCP, AWS, Azure, etc

When I tried setting up the prompt for a kubeconfig from AWS I just got this:

`(%{%F{4}%}⎈ %{%f%}|%{%F{1}%}arn:aws:eks:info%{%f%}:%{%F{6}%}default%{%f%})`

Thanks

**Comment by jonmosco** [comment]
This looks like a shell escape issue, not a cloud provider configuration (which should be a kubeconfig file).
