### ISSUE TITLE
Need some help setting up

### ISSUE THREAD

**Issue by swright-eti** [jonmosco/kube-ps1#157]
I am trying to set this up in bash for Ubuntu and I am not sure what I am doing wrong. 

I have this in my .bashrc file:
```
source ~/load-k8s-configs.sh
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$HOME/.kube/plugins:$PATH"

source ~/kube-ps1.sh
PS1='[\u@\h \W $(kube_ps1)]\$ '

```

I source the .bashrc file and my existing color set goes away, but I dont see any context information added to my prompt.

I have kubectl. CTX, and NS installed. 

```
[swright@swright-dev-09 ~ ]$ k ctx
clstr2.dev
cluster01.dev
k3s1.dev
n01.dev
triad60.demo
triad60.dev
triadgfm.dev
web.dev
```

Can you please let me know where I am going wrong?
Thanks.

**Comment by swright-eti** [comment]
You are right. I added ```_kube_ps1_get_context_ns``` to the ```kube_ps1()``` function and it started working. 

```
# Build our prompt
kube_ps1() {

  _kube_ps1_get_context_ns

  [[ "${KUBE_PS1_ENABLED}" == "off" ]] && return
  [[ -z "${KUBE_PS1_CONTEXT}" ]] && [[ "${KUBE_PS1_CONTEXT_ENABLE}" == true ]] && return

...
```

**Comment by cs8898** [comment]
Oh seems i forgot to add an other comment.

For me it got also working after adding the .Kube/condig File

I was using k3s but somewhere in the Update Cache Methode there is a Check Foto the KubeConfig File... That File was Missing because k3s uses it's own grom /etc ...

Could be a bit more performant

**Comment by jonmosco** [comment]
The application uses the kubectl configuration conventions, so it will expect either the environment variable `KUBECONFIG` to be set, or the existence of a `.kube/config` file.  Accounting for the locations of various config files would be beyond the scope of the application, but this could be solved by setting your `KUBECONFIG` to the location of the file regardless which distribution of Kubernetes you have running.

**Comment by jonmosco** [comment]
This issue seems to be resolved.
