### ISSUE TITLE
Minor typo in kubeon help message

### ISSUE THREAD

**Issue by TheAnalogyGuy** [jonmosco/kube-ps1#158]
https://github.com/jonmosco/kube-ps1/blob/e9e36d40580d0159cbb627229e0bf7eb10a52710/kube-ps1.sh#L288 minor type - it should read "With no arguments, turn **on** kube-ps1 status for this shell instance (default)." (instead of "off")

**Comment by jonmosco** [comment]
Good find, thank you!
