### ISSUE TITLE
KUBE_PS1_SEPARATOR not working

### ISSUE THREAD

**Issue by ahmetb** [jonmosco/kube-ps1#16]
```
(⎈ |test:default) ➜  ~ export KUBE_PS1_PREFIX=''
⎈ |test:default) ➜  ~ export KUBE_PS1_SEPARATOR=''
⎈ |test:default) ➜  ~ export KUBE_PS1_SEPARATOR='x'
⎈ |test:default) ➜  ~
```

**Comment by jonmosco** [comment]
Hmm, this works for me:

➜  ~(⎈ |tectonic-uat:kube-public) export KUBE_PS1_SEPARATOR='x'
➜  ~(⎈ xtectonic-uat:kube-public)

**Comment by jonmosco** [comment]
There was a spelling error that was corrected so you might need to do a pull.

**Comment by ahmetb** [comment]
you're right, turns out it was fixed.
