### ISSUE TITLE
Add variable to disable display context

### ISSUE THREAD

**Issue by Lxrdknows77** [jonmosco/kube-ps1#163]
It would be nice to have variable to disable display of context e.g **KUBE_PS1_CONTEXT_ENABLE**.

**Comment by jonmosco** [comment]
This already exists: `KUBE_PS1_CONTEXT_ENABLE="${KUBE_PS1_CONTEXT_ENABLE:-true}"`

**Comment by Lxrdknows77** [comment]
@jonmosco Sorry, my bad! Thanks.

**Comment by Lxrdknows77** [comment]
@jonmosco But I can't see it in the kube-ps1.sh

**Comment by Lxrdknows77** [comment]
There is not this var in the shell script
