### ISSUE TITLE
About `KUBE_PS1_SHELL`

### ISSUE THREAD

**Issue by chenrui333** [jonmosco/kube-ps1#166]
I noticed that [`KUBE_PS1_SHELL` got replaced with `_kube_ps1_shell_type`](https://github.com/Homebrew/homebrew-core/pull/116690), any design consideration about why not having `KUBE_PS1_SHELL`? Thanks!

Personally, I actually like `KUBE_PS1_SHELL` for environment introspection.

**Comment by jonmosco** [comment]
The change was made to reduce the export of environment variables to cut down on clutter and keeping things localized.  The function can still be used for env introspection, just run `_kube_ps1_shell_type` and you will get the value that was previously exported via `KUBE_PS1_SHELL`.  I did not see a reason to have that variable global.

**Comment by chenrui333** [comment]
> just run `_kube_ps1_shell_type` and you will get the value that was previously exported via `KUBE_PS1_SHELL`. I did not see a reason to have that variable global.

yeah, I can see that commit change, not sure why we used that variable to assert the formula test, but for now, I have already replaced it with `_kube_ps1_shell_type`. Thanks for clarifying it.
