### ISSUE TITLE
Running kube_ps1 in bash function returns blank

### ISSUE THREAD

**Issue by eogden93** [jonmosco/kube-ps1#171]
I have a function in my .bash_profile 

```bash
function kubeshell() {
    source /usr/bin/kube-ps1.sh
    PS1="[\u@\h \W $(kube_ps1)]\$ "
}
```

When I run this function it returns `[root@0232a48ae63e home ]$`
This is missing the colored output from `kube_ps1`

I've done some debugging and when I run `$(kube_ps1)` within the function it will return blank. However, running `kube_ps1` manually returns `(\033[38;5;4m⎈|\033[38;5;1mrancher-desktop:\033[38;5;6mN/A)`

My setup is a 3.15 Alpine docker image running on M1 Mac using bash (not zsh)

**Comment by roeniss** [comment]
Same here.
```
# ~/.zshrc
source kube_ps1.sh
echo $(kube_ps1)
```
When I launched a new terminal, the echo message is empty. But If I `source ~/.zshrc` again, it shows the prompt text.

I guess `kube-ps1` didn't update PS1 through `precmd`.

**Comment by roeniss** [comment]
by the way, https://github.com/jonmosco/kube-ps1/issues/168#issuecomment-1377737774 this trick works well. Put `PROMPT='$(kube_ps1)'$PROMPT` on last line in ~/.zshrc`.

**Comment by roeniss** [comment]
Aha. I'm using zsh.

**Comment by jonmosco** [comment]
Closing this issue.  If problem persists, please check out the README
