### ISSUE TITLE
A few questions about the documentation

### ISSUE THREAD

**Issue by davidshen84** [jonmosco/kube-ps1#172]
Hi,

Thanks for this great tool!

In the document, https://github.com/jonmosco/kube-ps1/#oh-my-zsh, if I use *oh-my-zsh*, do I still need to export my PROMPT variable? The document does not suggest so, but I found I have to add `export PROMPT='$(kube_ps1)'$PROMPT`.

Second, the download link to that OC tool is broken. I think https://www.okd.io/installation/ should be the new one.

Thanks

**Comment by jonmosco** [comment]
Yes, you have to add the `kube_ps1` function to your prompt.  This is in the documentation but not directly in the oh-my-zsh section: https://github.com/jonmosco/kube-ps1#zsh

I will update the plugins README in the oh-my-zsh repo to account for this, and also update the link for the oc tool download.  Thank you.
