### ISSUE TITLE
multiple prompts

### ISSUE THREAD

**Issue by kenhen93Evolve** [jonmosco/kube-ps1#176]
Hello,

I installed kube-ps1 on my mac using brew

I am using iterm2 with multiple tabs and my prompt shows multiple prompts

(⎈|arn:aws:eks:us-west-2:cluster:default)(⎈|arn:aws:eks:us-west-2:cluster:default)(⎈|arn:aws:eks:us-west-2:cluster:default)(⎈|arn:aws:eks:us-west-2:cluster:default)(⎈|arn:aws:eks:us-west-2:cluster:default)(⎈|arn:aws:eks:us-west-2:cluster:default)

my .zshrc looks like

```
[[ $PROMPT_COMMAND =~ _kube_ps1_update_cache ]] || PROMPT_COMMAND="_kube_ps1_update_cache;${PROMPT_COMMAND:-:}"

function get_cluster_short() {
  echo "$1" | cut -d / -f1
}

KUBE_PS1_CLUSTER_FUNCTION=get_cluster_short

source "/opt/homebrew/opt/kube-ps1/share/kube-ps1.sh"
PS1='$(kube_ps1)'$PS1
```

What am I doing wrong?

**Comment by kenhen93Evolve** [comment]
Seems like this happen if I source my .zshrc multiple times as I tinker with the setting. If I open a new tab it is ok.

**Comment by jonmosco** [comment]
Can't read the .zshrc file clearly, can you make it a code block?

**Comment by kenhen93Evolve** [comment]
Sorry, just updated the first post

**Comment by jonmosco** [comment]
Not sure why you are setting the `$PROMP_COMMAND` external of sourcing kube-ps1?

**Comment by kenhen93Evolve** [comment]
I got that from another one of your support posts.

**Comment by jonmosco** [comment]
Ok.  If you remove it, does that fix your issue?

**Comment by kenhen93Evolve** [comment]
The issue is not happening anymore
