### ISSUE TITLE
Hide no cluster and default namespace option

### ISSUE THREAD

**Issue by giautm** [jonmosco/kube-ps1#177]
Hello, I would like to have a built-in flag to disable display `kube_ps1` result for unset context and default. For now, I used both `KUBE_PS1_CLUSTER_FUNCTION` and `KUBE_PS1_NAMESPACE_FUNCTION` to do that as in [my theme](https://gist.github.com/giautm/b767c5200a7e0b2d1ae0baf4af64cdd6)

But it's more easy if we can disable just via an env. Thank you,

<img width="1004" alt="Screenshot 2023-07-21 at 11 02 35" src="https://github.com/jonmosco/kube-ps1/assets/12751435/d34d293d-681a-4fb6-8dc3-2331c2393907">

**Comment by jonmosco** [comment]
Have you looked at the `kubeon` and `kubeoff` functions?    https://github.com/jonmosco/kube-ps1?tab=readme-ov-file#enablingdisabling

**Comment by jonmosco** [comment]
Functionality provided by the builtin `kube{on,off}` functions.
