### ISSUE TITLE
Dynamic context colors

### ISSUE THREAD

**Issue by Maxence-v** [jonmosco/kube-ps1#178]
Hello,

I'm on zsh MacOS.
I use theohmyzsh plugin.

I want to set context colors dynamically.

For ex : if context contains prod: red, pre-prod OR dev: yellow, local: red.

Do you know how can i do this ?

**Comment by jonmosco** [comment]
Colors can be set using the environment variable as listed in the README.  For dynamic coloring like this, I would suggest using the `KUBE_PS1_CLUSTER_FUNCTION` and the `KUBE_PS1_NAMESPACE_FUNCTION`.

**Comment by jonmosco** [comment]
Solution explained.  Closing issue.

**Comment by credativ-dar** [comment]
@Maxence-v that sounds like a great idea to prevent mistakes, could you share your solution?
