### ISSUE TITLE
Add support for Warp

### ISSUE THREAD

**Issue by johanhaleby** [jonmosco/kube-ps1#181]
It would be great to have support for [Warp](https://www.warp.dev/). I'm using zsh (ohmyzsh) in Warp as well, but the prompt doesn't show up after running `kubeon`. See https://stackoverflow.com/questions/76903929/how-to-get-kube-ps1-to-work-in-wrap-terminal.

**Comment by jonmosco** [comment]
This request is out of scope for this project.   Their development for integrations like k8s is discussed here: https://docs.warp.dev/appearance/prompt#kubernetes
