### ISSUE TITLE
Couldn't Show ☸️ in My Prompt

### ISSUE THREAD

**Issue by AbbyDeng** [jonmosco/kube-ps1#183]
hey, thank you for this tool and sorry if this is a stupid question:

i can get all the other settings right but still can’t show this emoji ☸️ in my prompt
my `.zshrc`:
```
KUBE_PS1_CTX_COLOR=magenta
KUBE_PS1_SUFFIX_COLOR=null
KUBE_PS1_SYMBOL_USE_IMG=true
```

screenshot of my terminal:
<img width="357" alt="image" src="https://github.com/jonmosco/kube-ps1/assets/8296117/4732bf95-5e96-45f7-acee-6e2c93289157">

i installed a nerd font by `brew install --cask font-code-new-roman-nerd-font` and changed it in my iTerm2
and it still looks like this:
<img width="309" alt="image" src="https://github.com/jonmosco/kube-ps1/assets/8296117/26e71418-93a9-457a-9cc2-c97a5fbb9e88">

**Comment by AbbyDeng** [comment]
for future readers, this one fixed this issue:
https://github.com/jonmosco/kube-ps1/issues/117#issuecomment-603557023

```
KUBE_PS1_SYMBOL_ENABLE=true
KUBE_PS1_SYMBOL_DEFAULT=$'\u2638\ufe0f '
KUBE_PS1_SYMBOL_USE_IMG=false
```

**Comment by ialidzhikov** [comment]
Update:

I had to use the following config to make the emoji work with iterm2, zsh 5.9:
```
KUBE_PS1_SYMBOL_ENABLE=true
_KUBE_PS1_SYMBOL_DEFAULT=$'\u2638\ufe0f '
```

It seems that the `KUBE_PS1_SYMBOL_DEFAULT` was renamed to `_KUBE_PS1_SYMBOL_DEFAULT`.
