### ISSUE TITLE
Character not in range

### ISSUE THREAD

**Issue by memark** [jonmosco/kube-ps1#187]
In some contexts when starting my shell (for example when using `mtm`), I get this:
```
/opt/homebrew/opt/kube-ps1/share/kube-ps1.sh:27: character not in range
/Users/memark/.zshrc:122: command not found: kubeoff
```

Line 27 is this
```
_KUBE_PS1_SYMBOL_DEFAULT=${_KUBE_PS1_SYMBOL_DEFAULT:-$'\u2388'}
```

Any idea why it's failing (and only sometimes)?

**Comment by Startouf** [comment]
Duplicate of https://github.com/jonmosco/kube-ps1/issues/80 ?

Have you added the lang flags before initializing your plugins ?

**Comment by memark** [comment]
Thanks, it was indeed a duplicate. The LC_ALL flag did the thing. (Already had LANG.) Still don't know why it worked sometimes though, but that's for another time.
