### ISSUE TITLE
side-effect/overriden environment variables

### ISSUE THREAD

**Issue by ahmetb** [jonmosco/kube-ps1#19]
the following doesn't work for two reasons:

```sh
# .zshrc file:
export KUBE_PS1_PREFIX='['
export KUBE_PS1_SUFFIX=']'
source "$HOME/workspace/dotfiles/kube-ps1.sh"
```

1. it ignores my settings
2. replaces the passed value with the defaults `(` and `)`.

```
(⎈ |docker-for-desktop:default) ➜  ~ env | grep KUBE
KUBE_PS1_PREFIX=(
KUBE_PS1_SUFFIX=)
```

ideally the order of `export` and `source` shouldn't matter in this case I think. 

If I move export after sourcing, it works.

**Comment by jonmosco** [comment]
Agreed, another great find. https://github.com/jonmosco/kube-ps1/commit/247ad97499eec282812a8de6ee8e93f921f30b5b should address this issue.

**Comment by jonmosco** [comment]
Did you get a chance to test this out?

**Comment by ahmetb** [comment]
yeah, works fine now, thanks!
