### ISSUE TITLE
Multiple prompts if I source .zshrc

### ISSUE THREAD

**Issue by kenfringe** [jonmosco/kube-ps1#190]
```
(⎈cluster:default)@MacBook-Pro ~ % source ~/.zshrc
(⎈|cluster:default))(⎈|cluster:default)@MacBook-Pro ~ % source ~/.zshrc
(⎈|cluster:default))(⎈|cluster:default))(⎈|cluster:default))@MacBook-Pro ~ %
```

```
function` get_cluster_short() {
  echo "$1" | cut -d / -f1
}

KUBE_PS1_CLUSTER_FUNCTION=get_cluster_short

source "/opt/homebrew/opt/kube-ps1/share/kube-ps1.sh"
PS1='$(kube_ps1)'$PS1
```

Why is this happening?

**Comment by jonmosco** [comment]
Im not sure what your shell configuration looks like, but it looks like on first glance kube-ps1.sh is being sourced two times somewhere.  Try to disable all customization and add the prompt by itself to make sure it works properly, then adding in more customizations.

**Comment by jonmosco** [comment]
Closing this issue.  Suspected environment configuration issue.
