### ISSUE TITLE
Keep kubeoff as default when opening new terminal

### ISSUE THREAD

**Issue by codenio** [jonmosco/kube-ps1#191]
Hi, 

On opening new terminal the kube-ps1 script keeps kubeon as default. i.e, it displays the cluster and namespace info in the prompt. Could this be changed to kubeoff as default ?

**Comment by jonmosco** [comment]
If you set the global flag with `kubeoff -g` it will not be displayed when opening a new terminal. 
See https://github.com/jonmosco/kube-ps1?tab=readme-ov-file#enablingdisabling

**Comment by jonmosco** [comment]
Closing.  This can be done with current functionality.
