### ISSUE TITLE
After `kubeoff -g`, subsequent `kubeon -g` does not affect already opened terminals

### ISSUE THREAD

**Issue by agronskiy** [jonmosco/kube-ps1#195]
The following set of steps:
1. disable globally using `kubeoff -g`
2. open terminal 1
3. open terminal 2
4. in terminal 1, enable globally `kubeon -g`
5. ==> in terminal 2, the prompt is not shown.

Reading the code, I see that after stage 1, every opened terminal implicitly (https://github.com/ohmyzsh/ohmyzsh/blob/4188b22aea3356a02768505103e42a96d18547a3/plugins/kube-ps1/kube-ps1.plugin.zsh#L56) gets _its own_ var `KUBE_PS1_ENABLED=off` (that is, steps 2 and 3 get their own copy of this var), which is obviously not affected by `kubeon -g` from another terminal at stage 4.

Is this conformant with the documentation? I think, the latter kind of implies, that the overriding of the global setting only happens if I _explicitly_ called `kubeon/kubeof`, but otherwise every open terminal should be respecting the global setting.

**Comment by agronskiy** [comment]
In other words, would something like 
```diff
diff --git a/plugins/kube-ps1/kube-ps1.plugin.zsh b/plugins/kube-ps1/kube-ps1.plugin.zsh
index 894e0f7..c25576b 100644
--- a/plugins/kube-ps1/kube-ps1.plugin.zsh
+++ b/plugins/kube-ps1/kube-ps1.plugin.zsh
@@ -53,8 +53,6 @@ elif [ "${BASH_VERSION-}" ]; then
 fi
 
 _kube_ps1_init() {
-  [[ -f "${KUBE_PS1_DISABLE_PATH}" ]] && KUBE_PS1_ENABLED=off
-
   case "${KUBE_PS1_SHELL}" in
     "zsh")
       _KUBE_PS1_OPEN_ESC="%{"
@@ -206,6 +204,7 @@ _kube_ps1_file_newer_than() {
 _kube_ps1_update_cache() {
   local return_code=$?
 
+  [ -z ${KUBE_PS1_ENABLED+x} ] && [[ -f "${KUBE_PS1_DISABLE_PATH}" ]] && return $return_code
   [[ "${KUBE_PS1_ENABLED}" == "off" ]] && return $return_code
 
   if ! _kube_ps1_binary_check "${KUBE_PS1_BINARY}"; then
@@ -336,6 +335,7 @@ kubeoff() {
 
 # Build our prompt
 kube_ps1() {
+  [ -z ${KUBE_PS1_ENABLED+x} ] && [[ -f "${KUBE_PS1_DISABLE_PATH}" ]] && return
   [[ "${KUBE_PS1_ENABLED}" == "off" ]] && return
   [[ -z "${KUBE_PS1_CONTEXT}" ]] && [[ "${KUBE_PS1_CONTEXT_ENABLE}" == true ]] && return
 

```
make the logic more "expected". 

To recap, that is -- if no _explicit_ call to `kubeon/kubeoff` was made, every open terminal respects the global setting. Thanks.

**Comment by jonmosco** [comment]
This is in the oh-my-zsh repo, so I will update the plugin to reflect the newest code base.  Thank you for reporting this issue!
