### ISSUE TITLE
empty KUBE_PS1_SEPARATOR not working

### ISSUE THREAD

**Issue by ahmetb** [jonmosco/kube-ps1#21]
export KUBE_PS1_SEPARATOR=''

when I specify that I still get the `|` character:

    {⎈ |test:default}

any other non-empty value works fine, however.

**Comment by jonmosco** [comment]
Hmm, this works for me:

jmosco at jmosco-005715 in ~ (⎈ |tectonic-prod:upstream-tools)
$ export KUBE_PS1_SEPARATOR=''

jmosco at jmosco-005715 in ~ (⎈ tectonic-prod:upstream-tools)
$

**Comment by ahmetb** [comment]
@jonmosco try doing it before `source kube-ps1.sh`

**Comment by jonmosco** [comment]
And 1dede0a07e44c53ccf13a1ee37dd6bc8ba03cf82

**Comment by ahmetb** [comment]
Is this fixing it only for the separator?

**Comment by jonmosco** [comment]
There are 2 commits that fix the issue.

**Comment by jonmosco** [comment]
I'm thinking about something different for this now.  If the user wants to enable/disable a prompt component, there shoud be an option for it:

KUBE_PS1_SEPARATOR_ENABLE=false

This way the variable can be set to a default like `|` , and overwritten with a different character if desired.  Thoughts?

**Comment by ahmetb** [comment]
Tbh doesn’t make a lot of sense to me. If I wanna disable it, I can always set it to empty string. Is it not possible to detect empty value vs unset variable?

**Comment by jonmosco** [comment]
Ok, think we are good to go.  Test away.

**Comment by ahmetb** [comment]
works good now, thanks!
