### ISSUE TITLE
bash error

### ISSUE THREAD

**Issue by viennaa** [jonmosco/kube-ps1#22]
In bash following lines are not working. Removing parts in brackets is work arounding it.

https://github.com/jonmosco/kube-ps1/blob/master/kube-ps1.sh#L31-L34

github.com/jonmosco/kube-ps1/kube-ps1.sh: line 31: conditional binary operator expected
github.com/jonmosco/kube-ps1/kube-ps1.sh: line 31: syntax error near `KUBE_PS1_PREFIX'
github.com/jonmosco/kube-ps1/kube-ps1.sh: line 31: `[[ -v KUBE_PS1_PREFIX ]] || KUBE_PS1_PREFIX="("'

**Comment by jonmosco** [comment]
Which version of bash are you using?

**Comment by jonmosco** [comment]
Can you confirm this is fixed?

**Comment by jonmosco** [comment]
Going to close this issue since it has been addressed.
