### ISSUE TITLE
Proposal: kubeon/kubeoff should only affect current session 

### ISSUE THREAD

**Issue by jonmosco** [jonmosco/kube-ps1#23]
Kubeon/off currently applies to all shells based off a file check.  

I think these functions could be more useful if they apply to the current session only.  This can be achieved by setting and unsetting a variable:

KUBE_PS1_DISABLE=true
unset KUBE_PS1_DISABLE
then test for this on kube_ps1

**Comment by jonmosco** [comment]
@ahmetb Thoughts on this?

**Comment by ahmetb** [comment]
I'm okay with it **unless** the way kubeon/kubeoff works changes.

I want a way to have easy way to turn on and off persistently across all terminal windows.

**Comment by noelbundick** [comment]
It would be a nice improvement to have k8s cluster/namespace status visible in one tmux pane, while leaving it hidden in other panes where I'm focused on git, cloud resources, etc.

**Comment by ahmetb** [comment]
@noelbundick are you looking for possibly a tmux status bar support?

**Comment by ahmetb** [comment]
I agree that there's good use case for both having it:
- persistently turn on/off (my use case, where I usually have max 2-3 terminals)
- transiently turn on/off (tmux/split panes use case, where you want one pane to be k8s)

I'm not sure how we can make both camps happy. Here's a proposal:

```
    kubeon   :    turn on kube-ps1 status for this shell
    kubeon -g:    turn on kube-ps1 status globally
    ...
```

I'm okay with using an extra `-g` to persist the setting. Then you should decide on the precedence (whether -g overrides or vice versa).

**Comment by noelbundick** [comment]
tmux status bar would be neat, but I like the `kubeon -g` proposal better. That covers any combinations of tmux/multiple terminals/etc. that I currently use. Making it an option lets me script & do whatever I want :)

**Comment by jonmosco** [comment]
This is what I have been working on.  I will hopefully have a patch in the next few days for this.

**Comment by jonmosco** [comment]
Here is the help info for kubeon and kubeoff.  Let me know what you think.

For kubeon:
```
kubeon -h
Toggle kube-ps1 prompt on

Usage: kubeon [-g | --global] [-h | --help]

With no arguments, turn off kube-ps1 status for this shell instance (default).

  -g --global  turn on kube-ps1 status globally
  -h --help    print this message
```
and kubeoff:
```
kubeoff -h
Toggle kube-ps1 prompt off

Usage: kubeoff [-g | --global] [-h | --help]

With no arguments, turn off kube-ps1 status for this shell instance (default).

  -g --global turn off kube-ps1 status globally
  -h --help   print this message
```

This way the help information will provide the details to avoid confusion.

**Comment by ahmetb** [comment]
Looks good.
