### ISSUE TITLE
Add support for aliases

### ISSUE THREAD

**Issue by johanhaleby** [jonmosco/kube-ps1#24]
When using kube-ps1 the prompt can be very long as seen in this example:

![image](https://user-images.githubusercontent.com/187029/35141621-c8731c66-fcfb-11e7-86c7-dff520bc8eef.png)

It would be create if one could create a shorter alias for the context (and possibly namespace as well).

For example:

```bash
KUBE_PS1_CONTEXT_ALIASES='gke_xxxxxxxxxxxxxxxxxxxxxxx_europe-west1-c_prod=prod, another_context=another'
```

thus rendering only `prod` instead of `gke_xxxxxxxxxxxxxxxxxxxxxxx_europe-west1-c_prod` and `another` instead of `another_context` as context name in the prompt.

**Comment by jonmosco** [comment]
This feature is available in kubectl with `kubectl config rename-context`:
https://github.com/kubernetes/kubernetes/issues/45131

Thanks for this suggestion, but I think the contexts should stay in the kubeconfig files so the logic for updating the prompt can stay intact.

**Comment by johanhaleby** [comment]
Thanks, `rename-context` is probably good enough for me now (didn't know about it!)

**Comment by jonmosco** [comment]
No problem, thanks for using the prompt!
