### ISSUE TITLE
Add ability to specify background color

### ISSUE THREAD

**Issue by johanhaleby** [jonmosco/kube-ps1#25]
I'd like to change the background color of prompt so it would be nice if this would be available as a configuration option. Currently I do like this to get it to work the way I want:

```
PROMPT=%{$bg[white]%}'$(kube_ps1)'$PROMPT
```

**Comment by jonmosco** [comment]
Support added in 44ac9e for zsh (bash soon).

Please test and let me know if this works for you.  You can set a background color with `KUBE_PS1_BG_COLOR=<color>`

**Comment by johanhaleby** [comment]
Works great in zsh! Thanks for adding support it.

**Comment by jonmosco** [comment]
This works now for bash.  Closing this issue.
