### ISSUE TITLE
Ability to hide namespace

### ISSUE THREAD

**Issue by johanhaleby** [jonmosco/kube-ps1#26]
Would it be possible and make sense to add an environment variable that hides the namespace? In my case I virtually never change the namespace so I might as well not show it.

**Comment by jonmosco** [comment]
Yes, that feature is build in via the KUBE_PS1_NS_ENABLE env variable.

Set that to false and it will disable the namespace:
`KUBE_PS1_NS_ENABLE=false`

**Comment by johanhaleby** [comment]
Oh somehow I missed that, sorry for the noise.
