### ISSUE TITLE
Enabling kube-ps1 messes up completion in zsh?

### ISSUE THREAD

**Issue by johanhaleby** [jonmosco/kube-ps1#27]
It looks like my zsh completion doesn't work as expected when the kube-ps1 prompt is enabled. This is the relavant parts of my `~/.zshrc` file:

```
KUBE_PS1_SYMBOL_USE_IMG=true
KUBE_PS1_SYMBOL_ENABLE=true
KUBE_PS1_SEPARATOR=' '
KUBE_PS1_PREFIX=''
KUBE_PS1_SUFFIX=''
KUBE_PS1_NS_ENABLE=false
source ~/.zsh/scripts/kube-ps1.sh
PROMPT='$(kube_ps1)'$PROMPT
# Disable kube prompt by default, enable with "kubeon"
kubeoff
```

The prompt now looks like this when I start a new window:
![image](https://user-images.githubusercontent.com/187029/35163247-6007b240-fd46-11e7-8038-f2bb66d167db.png)

If I enter `kubec` and press tab it's expanded to:
![image](https://user-images.githubusercontent.com/187029/35163300-8733b1f2-fd46-11e7-9a25-81c287fc9484.png)

But when I run `kubeon` and enter `kubec` and pressing tab I get this:
![image](https://user-images.githubusercontent.com/187029/35163374-c29ad3ec-fd46-11e7-8175-319e0bd6424c.png)

Notice the extra "k" that is inserted.

**Comment by jonmosco** [comment]
I get the same with that configuration.  Its the escape sequence handling when disabling features of the prompt.  Can you do a pull and try now and let me know?

**Comment by johanhaleby** [comment]
Yes it seems to work but now the image (![image](https://user-images.githubusercontent.com/187029/35181147-db04e49c-fdbc-11e7-8fbb-784251d061af.png)) is not shown. I see this with the same configuration as above:

![image](https://user-images.githubusercontent.com/187029/35181159-0cb3ad3e-fdbd-11e7-8388-f1a9bff05382.png)

**Comment by jonmosco** [comment]
efd38e6 should fix.  Please test and let me know.  

Good find!  The symbol had an extra space.

**Comment by johanhaleby** [comment]
Hmm I've just tried to download from master again but I still don't see the Kubernetes image symbol with the configuration mentioned above :/

**Comment by jonmosco** [comment]
hmm, what does `export | grep KUBE` show?

**Comment by johanhaleby** [comment]
It doen't show anything

**Comment by jonmosco** [comment]
Hmm, works for me when I enable/disable KUBE_PS1_SYMBOL_USE_IMG=true

<img width="741" alt="screen shot 2018-01-21 at 2 04 57 pm" src="https://user-images.githubusercontent.com/1970496/35197857-1b6c522a-feb4-11e7-8d0f-24fb42ba5476.png">

**Comment by jonmosco** [comment]
Last push was not successful, please try again.  Sorry about that.

**Comment by johanhaleby** [comment]
Sorry it still doesn't work for me with this configuration:

```
KUBE_PS1_SYMBOL_USE_IMG=true
KUBE_PS1_SYMBOL_ENABLE=true
KUBE_PS1_SEPARATOR=' '
KUBE_PS1_PREFIX=''
KUBE_PS1_SUFFIX=''
KUBE_PS1_NS_ENABLE=false
source ~/.zsh/scripts/kube-ps1.sh
PROMPT='$(kube_ps1)'$PROMPT
# Disable kube prompt by default, enable with "kubeon"
kubeoff
```

**Comment by jonmosco** [comment]
I'm not sure what your agnoster setup looks like, but I can get it to work with your configuration and that particular theme:
<img width="519" alt="screen shot 2018-01-22 at 8 38 25 am" src="https://user-images.githubusercontent.com/1970496/35223538-b548f8a8-ff4f-11e7-936c-46e425caeba0.png">

**Comment by johanhaleby** [comment]
Ah ok, then it's probably something fishy at my side. Thanks for your help, I'm closing.

**Comment by jonmosco** [comment]
No problem.  Let me know if the tab completion is fixed once you get it working.  

Thanks for using this and the testing!

**Comment by johanhaleby** [comment]
Tab is indeed working as expected! Thanks for a great project :)
