### ISSUE TITLE
Kubernetes context not loaded on shell creation

### ISSUE THREAD

**Issue by dieterdemeyer** [jonmosco/kube-ps1#28]
Hello,

I've sourced the kube-ps1.sh file in my bash configuration and modified my bash prompt to include the kubernetes context information.
However, it seems that when I open a new shell for the first time, the kubernetes context is not loaded. Only after hitting 'Enter' on the command line, is the context loaded.
See my prompt output below.

```
Last login: Sun Jan 21 19:25:42 on ttys002
(⎈ |:) » ~
(⎈ |docker-for-desktop:default) » ~
```

Any idea what could be wrong in my configuration ?

Thanks.

**Comment by jonmosco** [comment]
Hm/m.  Can you paste your configuration that sources this file?  Are you using kubectl ?

**Comment by dieterdemeyer** [comment]
Yes, I'm using kubectl.
I've tried both sourcing your file directly from `.bash_prompt` and from `.bash_profile`.
Here is a snippet from my `.bash_prompt ` that calls the command:

```
function prompt_command() {
  #source ~/.profile.d/kube-ps1.sh
  prompt_exit_status
  PROMPT_START=$START
  PROMPT_END=" "

  update_current_git_vars

  if [ -n "$__CURRENT_GIT_STATUS" ]; then
    STATUS="$GIT_PROMPT_PREFIX$GIT_PROMPT_BRANCH$GIT_BRANCH$ResetColor"

    if [ -n "$GIT_REMOTE" ]; then
      STATUS="$STATUS$GIT_PROMPT_REMOTE$GIT_REMOTE$ResetColor"
    fi

    STATUS="$STATUS$GIT_PROMPT_SEPARATOR"
    if [ "$GIT_STAGED" -ne "0" ]; then
      STATUS="$STATUS$GIT_PROMPT_STAGED$GIT_STAGED$ResetColor"
    fi

    if [ "$GIT_CONFLICTS" -ne "0" ]; then
      STATUS="$STATUS$GIT_PROMPT_CONFLICTS$GIT_CONFLICTS$ResetColor"
    fi
    if [ "$GIT_CHANGED" -ne "0" ]; then
      STATUS="$STATUS$GIT_PROMPT_CHANGED$GIT_CHANGED$ResetColor"
    fi
    if [ "$GIT_STASHED" -ne "0" ]; then
      STATUS="$STATUS$GIT_PROMPT_STASHED$GIT_STASHED$ResetColor"
    fi
    if [ "$GIT_UNTRACKED" -ne "0" ]; then
      STATUS="$STATUS$GIT_PROMPT_UNTRACKED$GIT_UNTRACKED$ResetColor"
    fi
    if [ "$GIT_CLEAN" -eq "1" ]; then
      STATUS="$STATUS$GIT_PROMPT_CLEAN"
    fi
    STATUS="$STATUS$ResetColor$GIT_PROMPT_SUFFIX"

    PS1="$PROMPT_START$STATUS$PROMPT_END"
    PS1="$(kube_ps1) $PS1"
    #PS1="$Blue\[$(tput sc; right_prompt; tput rc)\]$ResetColor$PROMPT_START$STATUS$PROMPT_END"
  else
    PS1="$PROMPT_START$PROMPT_END"
    PS1="$(kube_ps1) $PS1"
    #PS1="$Blue\[$(tput sc; right_prompt; tput rc)\]$ResetColor$PROMPT_START$PROMPT_END"
  fi
}
```

**Comment by jonmosco** [comment]
Why do you have the source ~/.profile.d/kube-ps1.sh commented out?

What happens if you just set a simple bash prompt to test? 

`PS1="\u \W @ \h $(kube_ps1) \$ " `

**Comment by dieterdemeyer** [comment]
It's commented out because I've sourced it in `.bash_profile` instead of `.bash_prompt`.
Using a simple bash prompt as you suggested results in the same behaviour.

**Comment by dieterdemeyer** [comment]
Also, I noticed that when switching from one Kubernetes context to another, the new context is also not reflected in the bash prompt.
Only after hitting 'Enter' explicitly will the new context be shown in the prompt.

**Comment by jonmosco** [comment]
I think the problem was with the ordering of the PROMPT_COMMAND with kube-ps1.  

Also, I did not above when typing a simple prompt, but make sure to escape the `$` in double quotes so the prompt gets refreshed.  

Please try this now and let me know if it solves the issue.

**Comment by dieterdemeyer** [comment]
Escaping the `$` in double quotes seems to be the fix for both problems, so shell creation and switching contexts.

**Comment by vonneudeck** [comment]
Could you please tell me which $ you are referring to?
I think I am trying to "" the wrong one.

**Comment by dieterdemeyer** [comment]
@vonneudeck ,

I changed `PS1="$(kube_ps1) $PS1"` to `PS1="\$(kube_ps1) $PS1"` which seems to work for me.
So, escaping the call to the `kube_ps1` function.

**Comment by jonmosco** [comment]
Yes in double quotes it will need escaped.  I did not put that in the simple prompt earlier by mistake, but it is in the README.

**Comment by vonneudeck** [comment]
Thanks for your help. Now it works fine for me as well.

**Comment by jonmosco** [comment]
Great!  Thanks for using this and the feedback.  Much appreciated!

**Comment by stiliajohny** [comment]
> @vonneudeck ,
> 
> I changed `PS1="$(kube_ps1) $PS1"` to `PS1="\$(kube_ps1) $PS1"` which seems to work for me.
> So, escaping the call to the `kube_ps1` function.


my `kube_ps1` was not refreshing until I was `source ~/.zshrc` as well 

after escaping `$` is fine 
I changed `PS1="$(kube_ps1)"` to `PS1="\$(kube_ps1)"`
