### ISSUE TITLE
error when current-context is not set

### ISSUE THREAD

**Issue by ahmetb** [jonmosco/kube-ps1#29]
If current-context is not set on kubectl, starting a new shell gives error:

```
error: current-context is not set
kubectl context is not set
```

**Comment by jonmosco** [comment]
Error output from kubectl redirected to /dev/null in 44ac9e

**Comment by ahmetb** [comment]
I'm still seeing a message saying "kubectl current-context is not set".

I shouldn't be seeing any error message if there's no current context. Instead of showing `{⎈ |:}` maybe just show `{⎈ N/A|:N/A} `.

**Comment by jonmosco** [comment]
Agreed.  Updated kube-ps1.sh and the README to reflect this change.   3809ca1

**Comment by jonmosco** [comment]
Thanks again for testing and the suggestion!

**Comment by ahmetb** [comment]
You can use "fixes #N" in your commit msg to close issues automatically fwiw.

Thanks for fixing.

**Comment by jonmosco** [comment]
Oh yes, good to know, thank you.
