### ISSUE TITLE
seeing empty namespace

### ISSUE THREAD

**Issue by ahmetb** [jonmosco/kube-ps1#3]
`kubectl config view --minify  --output 'jsonpath={..namespace}'` can return empty if you haven't explicitly set the namespace.

I'm seeing `(⎈ |minikube:)` in my prompt, for instance. Setting a namespace fixes it. So maybe default to `"default"` if value is missing.

```
(⎈ |minikube:) ➜  ~ git:(master) kubens default
Context "minikube" modified.
Active namespace is "default".
(⎈ |minikube:default) ➜  ~ git:(master)
```

**Comment by jonmosco** [comment]
if [[ -z $(${KUBE_BINARY} config view --minify --output 'jsonpath={..namespace}') ]]; then
   KUBE_PS1_NAMESPACE="$(${KUBE_BINARY} config view --minify --output 'jsonpath={..namespace}')"
 else
   KUBE_PS1_NAMESPACE="default"
 fi

I saw the same behavior as well, just was unsure that setting the default to 'default' was going to be accepted.  Is there a case where its not default if undefined ?

**Comment by jonmosco** [comment]
Remove the -z actually, just test it has output.  Verified:

jmosco at jmosco-005715 in ~ (⎈ |minikube:)
$ prompt_k8s

jmosco at jmosco-005715 in ~ (⎈ |minikube:default)
$ kubens
default
kube-public
kube-system

jmosco at jmosco-005715 in ~ (⎈ |minikube:default)
$ kubens kube-public
Context "minikube" modified.
Active namespace is "kube-public".

**Comment by ahmetb** [comment]
> if [[ -z $(${KUBE_BINARY} config view --minify --output 'jsonpath={..namespace}') ]]; then
> KUBE_PS1_NAMESPACE="$(${KUBE_BINARY} config view --minify --output 'jsonpath={..namespace}')"
> else
> KUBE_PS1_NAMESPACE="default"
> fi

haha definitely don't do this, you 're calling kubectl twice just to get the same value :) 

`${VARIABLE:-default}` should just work here.

**Comment by jonmosco** [comment]
Yes, ok lol.

**Comment by jonmosco** [comment]
KUBE_PS1_NAMESPACE="$(${KUBE_BINARY} config view --minify --output 'jsonpath={..namespace}')"
 KUBE_PS1_NAMESPACE="${KUBE_PS1_NAMESPACE:-default}"

**Comment by ahmetb** [comment]
yeah, but ideally I'd like to see #4 fixed :)

**Comment by jonmosco** [comment]
Going to work on that one now.  Thanks for all these fixes/suggestions!
