### ISSUE TITLE
KUBECONFIG ENV ignored

### ISSUE THREAD

**Issue by nicolerenee** [jonmosco/kube-ps1#30]
When using the `KUBECONFIG` environment variable to change the path to the kubeconfig file it results in the prompt not being updated.

``` 
~  (⎈ |minikube:default) export  KUBECONFIG=~/.kube/config-n10
~  (⎈ |minikube:default) kctx
kubernetes-admin@kubernetes
```

I would have expected my prompt to have changed to
```
~  (⎈ |kubernetes-admin@kubernetes:default)
```

**Comment by jonmosco** [comment]
It looks like you are having kubectx look at the available contexts after exporting a new KUBECONFIG, and not actually changing it.

After you export the new KUBECONFIG, what do you get when you look up the current-context with kubectl:

```
$ kubectl config current-context
```

When I do the same with a new configuration file and switch my current context, the prompt does update as expected:

```
~ (⎈ |docker-for-desktop:default) export KUBECONFIG=~/.kube/config

~ (⎈ |docker-for-desktop:default)  kubectx tectonic
Switched to context "tectonic".

~ (⎈ |tectonic:default)
```

**Comment by nicolerenee** [comment]
When I switch it changes my context to the one in the new file. It looks like if I switch between context in that file my prompt updates. But only if the file changes.

```
 ~
 export  KUBECONFIG=~/.kube/config-n10                   (⎈ |minikube:default)
 ~
 kubectl config current-context                          (⎈ |minikube:default)
lab
 ~
 kctx lab                                                (⎈ |minikube:default)
Switched to context "lab".
 ~
 kctx kubernetes-admin@kubernetes                        (⎈ |minikube:default)
Switched to context "kubernetes-admin@kubernetes".
 ~
 kctx lab                               (⎈ |kubernetes-admin@kubernetes:default)
Switched to context "lab".
 ~
                                                                (⎈ |lab:default)
```

**Comment by jonmosco** [comment]
Please let me know if this works for you.

**Comment by nicolerenee** [comment]
YAY that fixed it! Thanks!!

**Comment by jonmosco** [comment]
Thank you for testing and using this prompt!
