### ISSUE TITLE
kubeon/kubeoff not working as expected

### ISSUE THREAD

**Issue by ahmetb** [jonmosco/kube-ps1#33]
1. open terminal tab &rarr; kube-ps1 string shows (expected)
2. `kubeoff -g`&rarr;  hides kube-ps1 string (expected)
3. `kubeon` &rarr; ps1 string still does not show up (NOT EXPECTED)

**Comment by ahmetb** [comment]
4. `kubeon -g` &rarr; ps1 string still does not show up (also NOT EXPECTED)

**Comment by ahmetb** [comment]
Why is `kubeon`/`kubeoff` is deprecated?

**Comment by jonmosco** [comment]
I wanted to switch to a more consistent naming convention for them because
'kubeon' and 'kubeoff' felt a little ambiguous regarding other kube
commands.  Thoughts?  If you disagree, I am up for suggestions.

**Comment by ahmetb** [comment]
I opened #34 to discuss. I'm frustrated with the fact that there was no discussions and as the sole developer, you’ve been changing things constantly.

I just updated my local copy with the fix you made above and it's not fixed.
