### ISSUE TITLE
Why is kubeon/kubeoff deprecated now?

### ISSUE THREAD

**Issue by ahmetb** [jonmosco/kube-ps1#34]
kubeon/kubeoff no longer seems to work with comments indicating deprecation in the source code.

Was there a discussion about this? I’m lately a little frustrated in number of the ways the project is getting in my way of doing things.

I have developed kubectx/kubens so people set it up once and forget about it. So far I tend to think I achieved that. I have ideas to add there but I’ve been holding off on making major changes, because a lot of people tell me that it’s very much central to their day-to-day workflow.

I want to see the same from kube-ps1. However, so far my experience is reflecting it's been the case that things keep breaking, too many configurable knobs mostly untested, kubeon/kubeoff stops working either because of badly implemented state machine or some arbitrary deprecation.

I am no longer able to keep up with these changes. If you are seeking help or guidance on this project, I can provide support such as reviewing every single commit. But I can no longer stand the fact that this project is being pulled to different directions in many directions. I just want it to work.

**Comment by jonmosco** [comment]
Understood.  I am just trying to keep up with the changes and not break it for anyone and get it to a more stable spot without realizing how much it is being used.  I should have discussed this change, I agree.  I will revert that back but keep the functionality and try to be more consistent and on time with the changes being pushed.  This is my first project that has gained traction so I was just worried about stability and keeping up with the requests on here and from other sources. 

I appreciate all the help and feedback, and will try to make any changes properly tested and keep them as pull requests.  I don't want to lose the support, so any other insight you have would be very appreciated.  Again, I apologize for any inconvenience this has caused and will definitely discuss/test changes more thoroughly moving forward.

**Comment by ahmetb** [comment]
It sounds like you need help on governance of the project and you should not be the only person making changes to the project. I am happy to spare some time and help this project in case you are interested and willing to send a pull request for everything.

**Comment by jonmosco** [comment]
https://github.com/jonmosco/kube-ps1/pull/35

Care to take a look?  I would like to close this issue out and get moving on some testing and add a new changelog I generated as well.
