### ISSUE TITLE
on/off -g does not change the current session

### ISSUE THREAD

**Issue by ahmetb** [jonmosco/kube-ps1#37]
Starting state: `kubeoff -g`, run 3 shell windows

When I run `kubeon -g` on the current shell, I expect:
- current shell will turn on the PS1
- new shells will also have PS1 turned on
- already open shells (other tabs) will not change behavior when I hit return

Current behavior:
- current shell doesn't turn on PS1 **(UNEXPECTED)**
- new shells have PS1 turned on
- already open shells (other tabs) are turning it on  **(UNEXPECTED)**
------

Starting state: `kubeon -g`, run 3 shell windows

When I run `kubeoff -g` on the current shell, I expect:
- current shell will turn OFF the PS1
- new shells will also have PS1 turned OFF
- already open shells (other tabs) will not change behavior when I hit return

Current behavior:
- current shell doesn't turn off PS1  **(UNEXPECTED)**
- new shells have PS1 turned off
- already open shells (other tabs) are turning it on  **(UNEXPECTED)**

-----

Are my expectations not accurate? I kind of expected kubeon/kubeoff to work this way.

**Comment by jonmosco** [comment]
Yes those are correct expectations and it is very clear how you expect these controls to work now. 

I cleaned up the code and pull request is in for review; hopefully this will fix this once and for all.  

Thank you again for explaining this and being patient for a fix, I appreciate all the feedback as it has helped me with this project greatly.

**Comment by ahmetb** [comment]
No problem, I don't see the PR. Feel free to @ me there.

**Comment by jonmosco** [comment]
550aa60

**Comment by ahmetb** [comment]
I guess that's not a PR. :) That's fine. I'll try out.

**Comment by ahmetb** [comment]
Works as I expected now, thanks.
