### ISSUE TITLE
Faster ways to calculate context/namespace

### ISSUE THREAD

**Issue by ahmetb** [jonmosco/kube-ps1#5]
As seen in #4, `kube_ps1` shell function is slow (adds about 200 ms to every shell prompt users get).
This is because kubectl is not a fast program as one would think and it has a startup latency.

I have _a few_ ideas to make this faster. Here's my top idea that I think can work really fast:

- make `yq` (https://github.com/kislyuk/yq) (or another yaml parser) a mandatory dependency for this script
- figure out where the kubectl config file is ($KUBECONFIG if set, otherwise ~/.kube/config)
- read the namespace/context with a `cat $f | yq (..path-query..)`.

this should be muuuchhhh faster, I bet it can complete within 10 ms, which is an acceptable delay.

**Comment by jonmosco** [comment]
Making these changes now.  For change #2, I think it should test for $KUBECONFIG being set, the existence of ~/.kube/config, or else fail?  

KUBECONFIG_PS1="${KUBECONFIG:-~/.kube/config}"

KUBE_PS1_CLUSTER="$(KUBECONFIG=${KUBECONFIG_PS1} ${KUBE_BINARY} config view --minify --output 'jsonpath={..CurrentContext}')"

Or do you suggest reassigning KUBECONFIG?

**Comment by jonmosco** [comment]
or perhaps even just doing it one time per command:

KUBE_PS1_CLUSTER="$(KUBECONFIG=${KUBECONFIG:-$HOME/.kube/config} ${KUBE_BINARY} config view --minify --output 'jsonpath={..CurrentContext}')"

**Comment by ahmetb** [comment]
I don't understand what your $KUBECONFIG is doing above.

kubectl already knows how to pick up the $KUBECONFIG env var, and if unspecified it knows where to find it.

Your top problem is that you're calling `kubectl`. It is slow, I cannot afford 200 ms every time for kubectl to booth up, only to parse some value from a yaml file.

I tried `yq` (https://github.com/kislyuk/yq) but it is slow as hell (takes 200 ms to convert my config.yaml to json). We might need a Go program here that can only print the current-context, and its configured namespace.

**Comment by jonmosco** [comment]
Thats a good idea.  I have several clusters that are merged to a cluster-merge file, so parsing takes a while as well.

**Comment by jonmosco** [comment]
Im working on a Go program now for this, and its much faster using the k8s go client.  I will update as soon as I am done.

**Comment by ahmetb** [comment]
Honestly the best kind of tool you can have here is something that works without installing anything. Go is fast and has great startup time, but it ships as a few-MB binary. If perl/python/ruby can do it out-of-the-box and have comparable performance, you might be just ship the program as a `python -c "..."` statement in your ps1 script.

I recommend you do the Go implementation and write another in one of these languages (choose one that has a yaml library built-in) and compare. If we could parse it in bash/grep that would be a good choice too, but seems nontrivial.

**Comment by ahmetb** [comment]
@jonmosco how did it go with Golang?

**Comment by jonmosco** [comment]
Yes, but I did go a different route. 

I added a time check on the kubeconfig files, and only update the prompt if they have changed.  Since the operation of switching namespace and context will not happen every single press of enter, this improved standard time of the prompt. The tricky thing here was the time issues with bash and zsh, but that can also be improved at some point as well.

while :; do
    ts=$(date +%s%N) ; _kube_ps1_load ; tt=$((($(date +%s%N) - $ts)/1000000)) ; echo "Time taken: $tt milliseconds"
done
Time taken: 16 milliseconds
Time taken: 17 milliseconds
Time taken: 19 milliseconds
Time taken: 16 milliseconds
Time taken: 14 milliseconds
Time taken: 14 milliseconds
Time taken: 15 milliseconds
Time taken: 21 milliseconds
Time taken: 17 milliseconds
Time taken: 16 milliseconds
Time taken: 16 milliseconds
Time taken: 20 milliseconds
Time taken: 15 milliseconds
Time taken: 15 milliseconds
Time taken: 16 milliseconds
Time taken: 16 milliseconds

I will upload the code as soon as I clean it up, and would love any feedback you have.

**Comment by ahmetb** [comment]
Checking modtime sounds like a very good solution, you might after all end up not writing a separate program to parse the yaml. It's brilliant! Having this modtime saved to ~/.kube/config.mtime or something would be nice!

**Comment by jonmosco** [comment]
Ok, first iteration pushed.  Let me know what you think.  It will need lots of testing to ensure all the values are properly set and it works with zsh and bash.

**Comment by ahmetb** [comment]
Sorry didn't see your comment earlier! Tried now. I see empty context name after installing:

![image](https://user-images.githubusercontent.com/159209/34448134-9ec1332e-ec9f-11e7-972f-4b4021d213dd.png)

**Comment by ahmetb** [comment]
Fwiw when I'm on zsh, I see this:

```
$ echo $KUBE_PS1_SHELL
bash
```

**Comment by jonmosco** [comment]
Ok good to know, I will correct.  As always, thanks for testing.

**Comment by jonmosco** [comment]
Do you mind testing again?

**Comment by jonmosco** [comment]
Not the most elegant solution, but determining the shell is tricky so the simplest solution I could come up with was to just pass in the shell to the script:

```
source ~/kube-ps1.sh zsh
```

**Comment by ahmetb** [comment]
how about this:

```
$ basename $SHELL
zsh
```

**Comment by jonmosco** [comment]
The problem with that is it will reference the preferred shell, or the login shell.  $SHELL in my case even when switching to bash will always reference zsh.

```
echo "\$SHELL: ${SHELL}"
```

Inside a script, no matter which shell, this will always output /bin/zsh

```
OUR_SHELL="$(ps -o comm -p $$ | tail -1)"
```
That always returns sh (referenced by the shebang line).

I dont know of another programatic way to detect the shell other than passing in an argument.  Any other suggestions?

Also, if you pass in zsh, does it work as expected for you?

**Comment by ahmetb** [comment]
It works, but more installation work. How about this: $ZSH_VERSION and $BASH_VERSION. This seems to work based on the current shell that the user is in.

**Comment by jonmosco** [comment]
Ok, I think the problem was not launching bash with -l for login shell option.

Latest change has been pushed, let me know if this is sufficient.

**Comment by ahmetb** [comment]
ran into some issue, moving into another issue.
