### ISSUE TITLE
Whitespace is appended on tab completion

### ISSUE THREAD

**Issue by d-winter** [jonmosco/kube-ps1#51]
Hey,
thanks for this nice tool. I have just one problem: Everytime i hit tab to complete paths in zsh, it appends a whitespace and thus destroys further navigation with tab.
Any idea?
Here is my config (.zshrc):
```
source /usr/local/Cellar/kube-ps1/0.6.0/share/kube-ps1.sh
KUBE_PS1_SYMBOL_USE_IMG=true
KUBE_PS1_SYMBOL_ENABLE=true
KUBE_PS1_NS_ENABLE=true
PROMPT=$(kube_ps1)$PROMPT
KUBE_PS1_BG_COLOR=black
```

**Comment by jonmosco** [comment]
Hmm, this is interesting.  I will have to take a look at this and try to reproduce.

**Comment by jonmosco** [comment]
Which terminal emulator are you using?

**Comment by jonmosco** [comment]
Any updates or more information about this?  Have you tried this with the `--no-rc` options as described in the README?
