### ISSUE TITLE
wrong unicode symbols

### ISSUE THREAD

**Issue by ckorobov** [jonmosco/kube-ps1#52]
I see similar issue was reported but closed [here](https://github.com/jonmosco/kube-ps1/issues/20).
In my case (Linux Mint 18.3 Sylvia) it looks like this:

![image](https://user-images.githubusercontent.com/672957/40232945-35c53012-5aa1-11e8-94b5-210eb5e3cdb1.png)

I fixed it by using:
`      _KUBE_PS1_OPEN_ESC=$''
      _KUBE_PS1_CLOSE_ESC=$''
`
instead of:
 `      _KUBE_PS1_OPEN_ESC=$'\001'
      _KUBE_PS1_CLOSE_ESC=$'\002'
`

**Comment by jonmosco** [comment]
What are locale settings?  `$ locale`
What does the terminal print if you type `$ echo $'\2388'`

**Comment by ckorobov** [comment]
Here it is @jonmosco : 

> [08:30:33] ~ $ bash --norc
bash-4.3$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=nl_NL.UTF-8
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=nl_NL.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=nl_NL.UTF-8
LC_NAME=nl_NL.UTF-8
LC_ADDRESS=nl_NL.UTF-8
LC_TELEPHONE=nl_NL.UTF-8
LC_MEASUREMENT=nl_NL.UTF-8
LC_IDENTIFICATION=nl_NL.UTF-8
LC_ALL=
bash-4.3$ echo $'\2388'
88
bash-4.3$

![image](https://user-images.githubusercontent.com/672957/40345695-96fda886-5d9a-11e8-98df-6a9383c24e93.png)

**Comment by jonmosco** [comment]
Sorry, forgot the `u`
`$ echo $'\u2388'`

Which terminal emulator are you using?

**Comment by ckorobov** [comment]
It's terminator, but the same is in terminal. 

> [13:26:13] ~/Downloads $ echo $'\u2388'
⎈
[15:10:55] ~/Downloads $
[15:10:55] ~/Downloads $ terminator -v
terminator 0.98
[15:11:32] ~/Downloads $
[15:12:39] ~/Downloads $ gnome-terminal --version
GNOME Terminal 3.18.3
[15:12:42] ~/Downloads $

**Comment by jonmosco** [comment]
Do you see the same output when you have kube_ps1 in your actual prompt?

**Comment by ckorobov** [comment]
Yes @jonmosco , this is how I discoevred it.

**Comment by jonmosco** [comment]
Can you paste the portion of your bashrc that is calling kube_ps1?

**Comment by ckorobov** [comment]
source ~/.kube/kubectl-alias.sh
PS1='\D{[%T]} \w $(kube_ps1)\$ '
kubeoff

**Comment by jonmosco** [comment]
I can reproduce this on my machine with the correct output.

Did you try this first doing `bash --norc` then sourcing it and adding it to your prompt?

**Comment by ckorobov** [comment]
It's weird, now it's working fine in the prompt, but when I do echo it's still there. I guess we can close it:
![image](https://user-images.githubusercontent.com/672957/41702695-55b8c500-7531-11e8-8398-05c81c0ae6f2.png)

**Comment by jonmosco** [comment]
`\001` and `\002` are removed by bash and PS1 is drawn correctly.  The terminal in the case of the `echo` (gnome-terminal specifically) is not properly translating those chars.  I tested this in xterm, rxvt, and terminal and it works as expected.  This will even work in gnome-terminal with tmux as well.
