### ISSUE TITLE
Trim cluster name & namespace name

### ISSUE THREAD

**Issue by max-lobur** [jonmosco/kube-ps1#53]
For long cluster names & namespaces it takes a lot of space in a prompt:
`(kubernetes.us-west-2.dev.subenv.company.domain:application.namepsace)~prompt$`

Two options can be introduced:
- namespace trim len
- cluster trim len

setting both to 10 will end to:
``(kube.us-we..:applicatio..)~prompt$``
default: -1 (no trim)

**Comment by jonmosco** [comment]
For the cluster, you can do a rename (alias) with kubectl:
`kubectl config rename-context old_name new_name`

For the namespace, you can set up an alias in your dotfiles if necessary, but I dont want to get into limiting the name to a character limit; these names can provide a lot of information and you can always do an alias if necessary.

```sh
my_kube_ps1_alias() {
case $1 in
super-long-name) echo short;;
*) echo $1;;
esac
}

PS1='\u @ \h $(my_kube_ps1_alias $KUBE_PS1_CONTEXT) $>'
```

Check #24 as well.

**Comment by max-lobur** [comment]
Should work for me

**Comment by jonmosco** [comment]
Great, thanks for using this prompt!
