### ISSUE TITLE
Idea: make the namespace part blink for configured values

### ISSUE THREAD

**Issue by jack4it** [jonmosco/kube-ps1#54]
E.g. prod, production, etc.

Thoughts? If idea accepted, I can send a PR. 😇

**Comment by jonmosco** [comment]
Blink, as in `<blink>prod</blink>`, or did you mean blank?
If the former, I would rather not do text effects for the prompt.  If you want to enable this for your specific use case, you could always override the default vars for prompt:
`_KUBE_PS1_DEFAULT_BG=$'\033[5m`

Hope this helps.

**Comment by jack4it** [comment]
I meant blinking effect, for only the namespace part if the value is some configured values like prod or production. Or if we can provide a hook to customize the value used for the context or namespace. It would be great too.
