### ISSUE TITLE
Compatibility with oh-my-zsh

### ISSUE THREAD

**Issue by pavlos163** [jonmosco/kube-ps1#56]
Is this working with oh-my-zsh?

I am on a CentOS 7 machine and I have kubectl installed. I am using oh-my-zsh with `agnoster` as a theme.

I have added the following lines in my `.zshrc` file but nothing is happening when I `source `/.zshrc`:
```
source /path/to/kube-ps1.sh
PROMPT='$(kube-ps1)'$PROMPT
```

**Comment by rahulwa** [comment]
It works fine with oh-my-zsh. Below is my lines in `.zshrc`:
```
source "/usr/local/opt/kube-ps1/share/kube-ps1.sh"
PROMPT='$(kube_ps1)'$PROMPT
```

**Comment by jonmosco** [comment]
This works for me as well with oh-my-zsh.

**Comment by jonmosco** [comment]
Closing this issue.

**Comment by pavlos163** [comment]
I have exactly those lines in my `.zshrc` but can't see anything.

What themes are you using?

**Comment by jonmosco** [comment]
steeef.zsh-theme and robby_simple.zsh-theme

Can you try the prompt function first without oh-my-zsh to make sure its
not a configuration issue?

On Wed, Jun 20, 2018 at 7:55 AM, Pavlos Kosmetatos <notifications@github.com

**Comment by pavlos163** [comment]
I tried `zsh -f` and I just see the hostname:

```
user@host  ~/.oh-my-zsh/custom/plugins/kube-ps1   master  zsh -f
host%
```

**Comment by hbokh** [comment]
Must be ZSH-theme related.
Here `kube-ps1` not showing anything with `ZSH_THEME="powerlevel9k/powerlevel9k"`, but switching to some orther random theme like `ZSH_THEME="darkblood"` does.
