### ISSUE TITLE
command not found: add-zsh-hook

### ISSUE THREAD

**Issue by ahmetb** [jonmosco/kube-ps1#6]
I just downloaded from master and sourced, but I got:

    _kube_ps1_shell_settings:4: command not found: add-zsh-hook

I'm using oh-my-zsh on Mac.

**Comment by jonmosco** [comment]
Try it now, I believe it was autoload -U add-zsh-hook

**Comment by ahmetb** [comment]
Might be fixed now but I'm not sure as I'm on a different machine and seeing #8.

**Comment by jonmosco** [comment]
Switch exit to return

**Comment by jonmosco** [comment]
Switched exit to return
