### ISSUE TITLE
Display kube-ps1 prompt on the right side of the terminal

### ISSUE THREAD

**Issue by MTalalAnwar** [jonmosco/kube-ps1#61]
Could you possibly add the ability to display the kube_ps1 part of the prompt on the right side of the terminal (refer to screenshots).

This is how kube-ps1 looks in my terminal window:
![screen shot 2018-08-14 at 17 49 11](https://user-images.githubusercontent.com/3526562/44102710-a65af878-9fea-11e8-9d2b-3b319f756a0a.png)

And this is how [zsh-kubectl-prompt](https://github.com/superbrothers/zsh-kubectl-prompt) looks in my terminal window:
![screen shot 2018-08-14 at 17 49 50](https://user-images.githubusercontent.com/3526562/44102956-3d4e4654-9feb-11e8-9835-ce3dc1023750.png)

I think a custom option that would implement this functionality would also be extremely useful for people who use bullet train/powerline9k type themes where the prompt tends to get pretty long.

If there is already a way through which I can accomplish this by modifying my zsh config then do let me know, I'd highly appreciate that and would love to switch to over to kube-ps1.

**Comment by jonmosco** [comment]
Thank you for using the prompt!  I will include this in the README, thank you.
