### ISSUE TITLE
Is it possible to display the context & namespace somewhere else besides the current line?

### ISSUE THREAD

**Issue by asafpelegcodes** [jonmosco/kube-ps1#62]
I think I saw Jon demo this but I didn't see any information about it in the documentation.

Thanks

**Comment by jonmosco** [comment]
You could put the `kube_ps1` function in your right-hand prompt if you so desire.  This is not bound to any specific location in the prompt.

**Comment by jonmosco** [comment]
Going to close this since it can be added wherever the user specifies.
