### ISSUE TITLE
Do not load zsh modules

### ISSUE THREAD

**Issue by ahmetb** [jonmosco/kube-ps1#63]
https://github.com/jonmosco/kube-ps1/blob/7d06e2d6f0fc3f37c93714122fc9e4242baf48a5/kube-ps1.sh#L61-L62

This caused me at least 1 hour of debugging.

I was trying to figure out what the hell is loading zsh stat module, because it prevented me from calling the actual `stat` binary on my machine.

Please remove these lines. It's unexpected for a simple tool like kube-ps1 to have substantial side-effects like this.

**Comment by jonmosco** [comment]
I put these modules here to decrease the number of times zsh would have to shell out to external utilities.  This way, there is no need to call an external stat command no matter the platform this is being used on, and the redrawing/response latency was bothersome when doing so.  Use `command stat` if you need to force stat.

**Comment by ahmetb** [comment]
Have you measured the time calling the stat cmd vs module? I suspect the time would be near-negligible. Not to mention it only works on zsh?

**Comment by ahmetb** [comment]
I don't entirely know what changed. I started calling GNU stat as gstat in my system, so it doesn't affect me that much anymore.

**Comment by jonmosco** [comment]
The stat module loaded by zsh is now prefixed with a `z` to keep it from interfering with the systems stat.

**Comment by ahmetb** [comment]
SGTM.
