### ISSUE TITLE
Does not work when bash-git-prompt is already installed.

### ISSUE THREAD

**Issue by tigerinus** [jonmosco/kube-ps1#67]
Installed `bash-git-prompt` using `brew` before on my MacOS.

Here is how my ~/.bash_profile look like:

```
if [ -f $(brew --prefix)/etc/bash_completion ]; then
    source $(brew --prefix)/etc/bash_completion
fi

if [ -f $(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh ]; then
    __GIT_PROMPT_DIR=$(brew --prefix)/opt/bash-git-prompt/share
    source $(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh
fi

if [ -f $(brew --prefix)/opt/kube-ps1/share/kube-ps1.sh ]; then
    source $(brew --prefix)/opt/kube-ps1/share/kube-ps1.sh
    PS1='$(kube_ps1) $(__git_ps1)'
fi
```

However the new terminal window only shows git prompt.

I also tried putting the new lines in ~/.bashrc as said in the installation setup, but no luck.

I also tried putting the new lines before git-prompt setup, but no luck.

The only way to get kube_ps1 to work is to remove git-prompt.

**Comment by luisdavim** [comment]
It works for me, look here to see how I do it https://github.com/luisdavim/dotfiles/tree/master/files/bash

**Comment by jonmosco** [comment]
I can't reproduce this issue either.  Can you paste the output of `echo $PS1` ?

**Comment by vorozhko** [comment]
Had the same issue.
Fix for path:
`
GIT_PROMPT_START="\u@\h:\W$ ${Yellow}${PathShort}${ResetColor} \$(kube_ps1)"
`

**Comment by jonmosco** [comment]
I'll try to reproduce this via another system, but for now I can not.  I am not convinced this is an issue with the prompt and more of a configuration issue.

**Comment by tigerinus** [comment]
So what's the solution then?

I tried @vorozhko 's workaround but didn't have any luck.
