### ISSUE TITLE
Do not update ps1 cache if kube config's file type is symlink

### ISSUE THREAD

**Issue by bellatoris** [jonmosco/kube-ps1#70]
`stat` function does not check target file's changed time but symlink files' changed time. Therefore, `_kube_ps1_file_newer_than` function always return false if kube config file is symlink

```sh
_kube_ps1_file_newer_than() {
  local mtime
  local file=$1
  local check_time=$2

  if [[ "${KUBE_PS1_SHELL}" == "zsh" ]]; then
    mtime=$(stat +mtime "${file}")
  elif stat -c "%s" /dev/null &> /dev/null; then
    # GNU stat
    mtime=$(stat -c %Y "${file}")
  else
    # BSD stat
    mtime=$(stat -f %m "$file")
  fi

  [[ "${mtime}" -gt "${check_time}" ]]
}
```

**Comment by jonmosco** [comment]
Each of the stat functions have a `-L` which will check the symlinks.  I will add this feature, thanks for report!
