### ISSUE TITLE
Powerlevel9k support?

### ISSUE THREAD

**Issue by k4ch0** [jonmosco/kube-ps1#74]
There is support for powerlevel9k??

Thanks in advance

**Comment by snahelou** [comment]
You can use custom service
```
zsh_kubens(){
  echo -n "$(kube_ps1)"
}
POWERLEVEL9K_CUSTOM_SERVICE="zsh_kubens"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(.... custom_service)

```

**Comment by jonmosco** [comment]
Just looking at the project, it does look like you can add your own custom service as mentioned by @snahelou .  The prompt can be colored to match your style as well by changing the values as listed in the README.  Thank you.

**Comment by k4ch0** [comment]
Cool! Thanks
