### ISSUE TITLE
gstat: cannot stat '+mtime': No such file or directory

### ISSUE THREAD

**Issue by ahmetb** [jonmosco/kube-ps1#78]
I get this error `gstat: cannot stat '+mtime': No such file or directory` from kube-ps1 installed on zsh on macOS. I have GNU coreutils (which installs `gstat`) installed. And I also have a `alias stat=gstat` becuase I like GNU stat’s output better.

Doing this `alias stat=gstat` is causing kube-ps1 to fail.  When I `unalias stat` it works fine.

I think you need to make a release that calls `zstat`. My local copy of 0.6.0 (installed via brew) still has

```
  if [[ "${KUBE_PS1_SHELL}" == "zsh" ]]; then
    mtime=$(stat +mtime "${file}")
```

**Comment by jonmosco** [comment]
New release: 0.7.0 available.
