### ISSUE TITLE
Blocks loading of shell if current-context not set

### ISSUE THREAD

**Issue by ahmetb** [jonmosco/kube-ps1#8]
Using https://raw.githubusercontent.com/jonmosco/kube-ps1/07742d4960485ee473ad5179745cf0a98348d001/kube-ps1.sh

I just installed to another machine on zsh and sourcing the script blocks the shell from starting:

> 
![image](https://user-images.githubusercontent.com/159209/34464543-bb10a8a8-ee38-11e7-8071-6ecc9a1a495e.png)

It should work fine even if there’s no current-context set.

**Comment by jonmosco** [comment]
switched to return over exit

**Comment by jonmosco** [comment]
This should be fixed and closed.

**Comment by ahmetb** [comment]
Works great now, thanks for all your effort.

I will add a note to kubectx repo about this!

**Comment by jonmosco** [comment]
Thank you for all the testing!
