### ISSUE TITLE
Character not in range

### ISSUE THREAD

**Issue by PierluigiLenociAkelius** [jonmosco/kube-ps1#80]
`KUBE_PS1_SYMBOL_DEFAULT=${KUBE_PS1_SYMBOL_DEFAULT:-$'\u2388'}`

produce this error on my machine

`/usr/local/opt/kube-ps1/share/kube-ps1.sh:27: character not in range`

**Comment by jonmosco** [comment]
Which shell are you using and what happens if you do the following:

```bash
echo $'\u2388'
```

**Comment by PierluigiLenociAkelius** [comment]
`zsh --version
zsh 5.3 (x86_64-apple-darwin18.0)`

echo $'\u2388'
zsh: character not in range

**Comment by jonmosco** [comment]
What about the output of locale?

**Comment by PierluigiLenociAkelius** [comment]
`locale
LANG=
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=`

**Comment by PierluigiLenociAkelius** [comment]
I added `export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8` to my zshrc and now works.

**Comment by jonmosco** [comment]
Ok great!  I will close this issue.  Thank you for using the project!

**Comment by SohamJ** [comment]
If it helps, I was trying to do this in a Docker container and [this](https://stackoverflow.com/questions/28405902/how-to-set-the-locale-inside-a-debian-ubuntu-docker-container) stackoverflow thread helped me out. Thanks @pierluigilenoci on pointing me in the right direction :)

**Comment by Startouf** [comment]
Make sure those flags `LANG=...` are declared in your .szhrc BEFORE adding the zsh plugin.
