### ISSUE TITLE
Prompt hook added multiple times

### ISSUE THREAD

**Issue by Nuru** [jonmosco/kube-ps1#81]
In general, `kube-ps` is not protected against being initialized twice, as can happen when the user spawns a sub-shell. In particular [this line](https://github.com/jonmosco/kube-ps1/blob/v0.7.0/kube-ps1.sh#L71) unconditionally adds `_kube_ps1_update_cache` to `PROMPT_COMMAND` even if it already there. This results in `_kube_ps1_update_cache` being called multiple times.

In `bash`, one simple solution is to set the `PROMPT_COMMAND` this way:
```bash
[[ $PROMPT_COMMAND =~ _kube_ps1_update_cache ]] || PROMPT_COMMAND="_kube_ps1_update_cache;${PROMPT_COMMAND:-:}"
```
However, you may want to look into a more global way to avoid repeating the initialization steps if you are already installed in the shell.

**Comment by jonmosco** [comment]
Good find.  Going to add this:
```bash
[[ $PROMPT_COMMAND =~ _kube_ps1_update_cache ]] || PROMPT_COMMAND="_kube_ps1_update_cache;${PROMPT_COMMAND:-:}"
```
