### ISSUE TITLE
Context and Namespace does not update

### ISSUE THREAD

**Issue by fullstack-to** [jonmosco/kube-ps1#82]
Hi! I installed `kube-ps1` via Homebrew, unfortunately, the context name and the namespace does not update after switching it. 

I need to manually reload my `.bash_profile` to update the context and namespace name.

This is the part of me `.bash_profile` where I load and configure `kube-ps1`:

```
# kube-ps1
source /usr/local/Cellar/kube-ps1/0.7.0/share/kube-ps1.sh
kubeon -g
KUBE_PS1_SYMBOL_ENABLE=false
KUBE_PS1_NS_ENABLE=true
KUBE_PS1_CTX_COLOR=cyan
```

![2019-03-25 09 40 16](https://user-images.githubusercontent.com/48729826/54905760-10074c80-4ee2-11e9-9d97-190ec575dc43.gif)

**Comment by jonmosco** [comment]
Hmm, how are you using the KUBECONFIG file?  Env variable, or just in $HOME/.kube/config ?

**Comment by fullstack-to** [comment]
I didn't configure anything, so I suppose `kubectl` / `kube-ps1` is using the `$HOME/.kube/config` file.

**Comment by jonmosco** [comment]
Are you sourcing the bash_profile from your .bashrc file?  Is the shell you're using an interactive or a non-interactive shell?

**Comment by fullstack-to** [comment]
I only have a `.bash_profile`, my login shell is `/bin/bash` and I am using macOS 10.14.4.
I also tried to set the `KUBECONFIG` environment variable in the top of my `.bash_profile`:

```
# kubernetes
export KUBECONFIG=~/.kube/config
```

**Comment by jonmosco** [comment]
You might need a .bashrc file then if you are running an interactive shell; i'm not entirely sure how your setup is.

**Comment by fullstack-to** [comment]
The `.bashrc` file is ignored by macOS, it will look for the `.bash_profile` file.

This is the PS1 part of my `.bash_profile`:
```
# kubernetes
export KUBECONFIG=~/.kube/config

# kube-ps1
source /usr/local/Cellar/kube-ps1/0.7.0/share/kube-ps1.sh
kubeon -g

# ps1
PS1="${GREEN}m${RESET} @ ${PURPLE}n${RESET} $(kube_ps1) in ${YELLOW}\W${RESET}";
PS1+="\$(prompt_git \" ${RESET}on ${PURPLE}\" \"${YELLOW}\")";
PS1+=" ${GREEN}$ ${RESET}";

export PS1;
```

I also figured out, that I need to manually source my `.bash_profile` before `kube-ps1` prints anything.

**Comment by jonmosco** [comment]
It's not MacOS ignoring it, its how the bash shell works for reading configuration files.  This is from the man page:
```
       When an interactive shell that is not a login shell is started, bash reads and executes commands from /etc/bash.bashrc and ~/.bashrc, if these files exist.  This  may  be
       inhibited by using the --norc option.  The --rcfile file option will force bash to read and execute commands from file instead of /etc/bash.bashrc and ~/.bashrc.
```

My .bash_profile simply contains the following:
```
$ cat .bash_profile 
source ~/.bashrc
```

**Comment by fullstack-to** [comment]
I tried that already.
Is it possible that I am loading my K8s config in the wrong way?

**Comment by jonmosco** [comment]
kube-ps1 will look for the config file in various places:
```
  # kubectl will read the environment variable $KUBECONFIG
  # otherwise set it to ~/.kube/config
  local conf
  for conf in $(_kube_ps1_split : "${KUBECONFIG:-${HOME}/.kube/config}"); do
    [[ -r "${conf}" ]] || continue
    if _kube_ps1_file_newer_than "${conf}" "${KUBE_PS1_LAST_TIME}"; then
      _kube_ps1_get_context_ns
      return
    fi
  done
```

Does this differ from your setup?

**Comment by fullstack-to** [comment]
No, I have the `config` placed in `.kube`:

<img width="665" alt="Bildschirmfoto 2019-04-09 um 11 19 38" src="https://user-images.githubusercontent.com/48729826/55788866-703ce780-5ab9-11e9-953f-0742817f2cd4.png">

**Comment by pnowy** [comment]
@jonmosco I have the same issue. I've noticed that it appeared recently when I've added to my `.zshrc` the line with KUBECONFIG (needed configure different cluster from one of my customers):

```
KUBECONFIG=$KUBECONFIG:~/.kube/mysecondclusterworkconfig

...
...

source "/usr/local/opt/kube-ps1/share/kube-ps1.sh"
KUBE_PS1_PREFIX='['
KUBE_PS1_SUFFIX=']'
KUBE_PS1_SEPARATOR=''
RPROMPT='%{$fg[blue]%}$(kube_ps1)%{$reset_color%}'
```
Before with default KUBECONFIG (not modified on .zshrc and it means not defined) everything worked find. What do you suggest to fix that?

**Comment by jonmosco** [comment]
Are you exporting $KUBECONFIG anywhere else?  What does `echo $KUBECONFIG` produce?

I don't think this is an actual problem with kube-ps1 still, but a configuration issue but would like to help debug either way.

**Comment by pnowy** [comment]
@jonmosco I did not state that it's your fault :) Just trying to figure it out - maybe it helps someone else. To know the correct cluster and namespace is very important from my perspective. The missing update after switching is not safe because you could execute operation on the namespace where do you not expect to execute them.

The `echo $KUBECONFIG` in my case shows nothing (by default I don't have this value set). The problem appears when I set this value on my zshrc and that's probably because my original expression does not have the `~/.kube/config` value (this case`KUBECONFIG=$KUBECONFIG:~/.kube/myotherclusterconfig`)

So when I'm using the cluster which is defined on the default config then kube-ps1 doesn't work. In order to fix it I had to:
```
KUBECONFIG=$KUBECONFIG:~/.kube/config:~/.kube/myotherclusterconfig
```

So from my perspective this ticket could be closed but maybe it's worth to consider some kind of warning in case the default config file for user is no used for the kube-ps1 (but the kubectl doesn't have problem with it and switching to that cluster).

**Comment by jonmosco** [comment]
The cluster merge option is a good practice I've been using.  The leader file in the list of files will contain that just as you stated.  Example:
```
export KUBECONFIG=cluster-merge:cluster-config:cluster2-config
```

I wasn't saying you were making this my fault, im just trying to get all the use cases down so the utility can be a best solution (as you know, it is hard with the amount of shell config that can take place).  

I export KUBECONFIG in my dotfiles, and use that to merge them all into a context helper, this way kube-ps1 will be able to read the timestamp on that file when it looks in the `$HOME/.kube/` directory.

This article does a good job explaining as well:
https://coreos.com/blog/kubectl-tips-and-tricks

**Comment by pnowy** [comment]
@jonmosco thanks for the link to the article!

**Comment by fullstack-to** [comment]
I think i could solve the problem 🎉 

This is my current PS1 configuration (mind the backslash in front of the $(kube_ps1) subshell):

```
PS1="${GREEN}m${RESET} @ ${PURPLE}n${RESET} \$(kube_ps1) in ${YELLOW}\W${RESET}";
PS1+="\$(prompt_git \" ${RESET}on ${PURPLE}\" \"${YELLOW}\")";
PS1+=" ${GREEN}$ ${RESET}";

export PS1;
```

Once I remove the backslash, the cluster and namespace name is not updated.

**Comment by jonmosco** [comment]
Ah yes, the double quotes will only evaluate $PS1 when it is initialized.  So your fix to escape the value, or switch to single quotes will get it to work.

**Comment by VictorBHub** [comment]
I have the same issue and the above suggestions are not working for me.
manually sourcing again `kube-ps1.sh` solve this: 

> (⎈ |staging:default)user@my-mac ~ $ kubectx staging
Switched to context "staging".
(⎈ |staging:default)user@my-mac ~ $ kubectx demo
Switched to context "demo".
(⎈ |staging:default)user@my-mac ~ $ kubectx staging
Switched to context "staging".
(⎈ |staging:default)user@my-mac ~ $   source "/usr/local/opt/kube-ps1/share/kube-ps1.sh"
(⎈ |staging:default)user@my-mac ~ $ kubectx demo
Switched to context "demo".
(⎈ |demo:default)user@my-mac ~ $ kubectx staging
Switched to context "staging".
(⎈ |staging:default)user@my-mac ~ $


right now my `.bashrc` file contains the following:

> source "/usr/local/opt/kube-ps1/share/kube-ps1.sh"
PS1="\$(kube_ps1)"$PS1
if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi
source "/usr/local/opt/kube-ps1/share/kube-ps1.sh"

and my `.bash_profile` file ends with:

> [[ -f ~/.bashrc ]] && source ~/.bashrc

**Comment by tedmiston** [comment]
I'm having this issue as well when changing context or namespace via both `kubectl` and `kubectx` / `kubens`.

My PS1 assignment is single quoted per the recommendation above but the prompt does not update when switching clusters.  I've tried the snippet in `~/.bash_profile` or `~/.bashrc` which I then source into the bottom of `~/.bash_profile` (on macOS), but I am seeing the same result either way.

Re-sourcing the `kube-ps1.sh` does correctly update the context to reflect current-context for the next line and all commands forward for me as well.

I am using the plain vanilla config string recommended by the latest version of the [kube-ps1](https://formulae.brew.sh/formula/kube-ps1) package from Homebrew:

```
Make sure kube-ps1 is loaded from your ~/.zshrc and/or ~/.bashrc:
  source "/usr/local/opt/kube-ps1/share/kube-ps1.sh"
  PS1='$(kube_ps1)'$PS1
```

Shell session:

```shell
# expect context to change
(⎈ |docker-desktop:default)$ kubectx foo-bar
Switched to context "foo-bar".

# verify new context is active
(⎈ |docker-desktop:default)$ kubectl config current-context
foo-bar

# change context back
(⎈ |docker-desktop:default)$ kubectl config use-context docker-desktop
Switched to context "docker-desktop".
(⎈ |docker-desktop:default)$ kubectl config current-context
docker-desktop

# expected namespace to change
(⎈ |docker-desktop:default)$ kubens kube-system
Context "docker-desktop" modified.
Active namespace is "kube-system".
(⎈ |docker-desktop:default)$
```

Note that it works properly if I source `kube-ps1.sh` in my shell:

```shell
(⎈ |docker-desktop:default)$ source "/usr/local/opt/kube-ps1/share/kube-ps1.sh"

(⎈ |docker-desktop:default)$ kubectx foo-bar
Switched to context "foo-bar".

(⎈ |foo-bar:kube-system)$ kubectx docker-desktop
Switched to context "docker-desktop".
(⎈ |docker-desktop:default)$

(⎈ |docker-desktop:default)$ kubens kube-system
Context "docker-desktop" modified.
Active namespace is "kube-system".

(⎈ |docker-desktop:kube-system)$ kubens default
Context "docker-desktop" modified.
Active namespace is "default".
```

When running the debug command recommended in the readme, I get this:

```shell
$ bash --norc
bash: kube_ps1: command not found
```

(This error only occurs in the nested bash session, not the parent bash session.)

Any idea what might be going on? @jonmosco

**Comment by alex-hempel** [comment]
I am having exactly the same issue as @tedmiston. None of the pointers in this thread have helped. Updates made via kubectx and kubens do not update the prompt until I open a new shell, or re-source the kube-ps1.sh file.

**Comment by dkhandeshi** [comment]
@alex-hempel - thanks for the tip on the iTerm2 shell integration - I had the same issue and it is fixed now. Note also that `kubeon` and `kubeoff` did not work before and now they do (I had to always resort to `kubeoff -g` and `kubeon -g` before I changed the order of sourcing.
