### ISSUE TITLE
hook for invoking function before updating prompt

### ISSUE THREAD

**Issue by glensc** [jonmosco/kube-ps1#87]
_not sure is this better [direnv](https://direnv.net/) specific or [kube-ps1](https://github.com/jonmosco/kube-ps1)_

so, I want kube namespace changed on directory change.

With `direnv`, i'm able to setup `$K8S_NAMESPACE` shell variable, if kube-ps1 would had a hook to invoke before it grabs current namespace, i'd be done with the solution.

currently there exist `KUBE_PS1_CLUSTER_FUNCTION` and `KUBE_PS1_NAMESPACE_FUNCTION`, maybe `KUBE_PS1_DIRCHANGE_FUNCTION` or something?

xref:
- https://github.com/direnv/direnv/issues/495

**Comment by jonmosco** [comment]
This is an interesting idea, but I believe to be out of scope for the project.
