### ISSUE TITLE
How to increase the size of Kubernetes symbol?

### ISSUE THREAD

**Issue by acim** [jonmosco/kube-ps1#91]
I have tried to set KUBE_PS1_SYMBOL_USE_IMG to true, but this changes nothing. Linux Mint 19.1.

**Comment by jonmosco** [comment]
The image is part of our font selection.  To use the fancy image, it should just require kube-ps1.sh to be resourced.

**Comment by acim** [comment]
`source /usr/local/bin/kube-ps1.sh
KUBE_PS1_PREFIX=''
KUBE_PS1_SUFFIX=' '
KUBE_PS1_SEPARATOR=''
KUBE_PS1_SYMBOL_USE_IMG=true
KUBE_PS1_SYMBOL_COLOR='black'
KUBE_PS1_BG_COLOR='yellow'
KUBE_PS1_CTX_COLOR='black'
KUBE_PS1_NS_ENABLE=false
PROMPT='$(kube_ps1)'$PROMPT`

**Comment by jonmosco** [comment]
What is the result of trying to print the symbol to stdout?

```bash
echo $'\u2368'
```

Regardless of the output, the size of the glyph is determined by your font selection.

**Comment by acim** [comment]
![Screenshot from 2019-05-18 16-50-29](https://user-images.githubusercontent.com/2791202/57971348-13bcca00-798d-11e9-9130-5510ad36babd.png)

**Comment by acim** [comment]
It probably can't be better, not a big deal :)
