### ISSUE TITLE
kubeon/kubeoff commands not found

### ISSUE THREAD

**Issue by dijitali** [jonmosco/kube-ps1#92]
The documentation and demo video for this repo shows the usage of `kubeon` and `kubeoff` to enable/disable this tool.

Whilst the main tool works OK, the on/off commands don't appear to be functional for me:
```
(⎈ my-cluster:my-namespace)➜  ~ kubeoff
zsh: command not found: kubeoff
```

#34 seems to suggest they were removed but were re-added?  Should we be using them or is there some other way of doing this now?

For reference: I've installed via the [oh-my-zsh plugin here](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/kube-ps1).

**Comment by jonmosco** [comment]
The oh-my-zsh plugin has not been updated in a while, therefore does not contain those commands. I will work on getting that PR in.

**Comment by LearningOwl** [comment]
Any update on this ?

**Comment by jonmosco** [comment]
PR submitted to oh-my-zsh.
